"""Type stubs for :mod:`openswmm.engine._controls`."""

from collections.abc import MutableSequence
from typing import Any, NamedTuple, Tuple, Union

from ._solver import Solver


_Key = Union[int, str]


class ControlRule(NamedTuple):
    id: str
    text: str


class Controls(MutableSequence[ControlRule]):
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: Any) -> Any: ...
    def __setitem__(self, idx: Any, value: Any) -> None: ...
    def __delitem__(self, idx: Any) -> None: ...
    def insert(self, idx: int, value: Any) -> None: ...
    def append(self, value: Any) -> None: ...
    def clear(self) -> None: ...
    def set_link_setting(self, link: _Key, setting: float) -> None: ...
    def set_link_status(self, link: _Key, *, closed: bool) -> None: ...
    def validate_message(self, rule_text: str) -> Tuple[bool, str]: ...
