"""Type stubs for :mod:`openswmm.engine._datetime`.

Low-level Python bindings around the SWMM DateTime conversion C API
declared in ``openswmm_datetime.h``. SWMM's native DateTime is a ``double``
whose integer part is days since 1899-12-30 and fractional part is the
time-of-day fraction.
"""


def encode_date(year: int, month: int, day: int) -> float: ...
def encode_time(hour: int, minute: int, second: int) -> float: ...
def decode_date(value: float) -> tuple[int, int, int]: ...
def decode_time(value: float) -> tuple[int, int, int]: ...
def add_seconds(value: float, seconds: float) -> float: ...
def time_diff(value1: float, value2: float) -> int: ...
