"""Type stubs for :mod:`openswmm.engine._exceptions`."""

from typing import Optional

from ._enums import ErrorCode


class EngineError(Exception):
    code: int
    code_enum: ErrorCode
    message: str

    def __init__(self, code: int, message: str = ...) -> None: ...
    def __repr__(self) -> str: ...


class BadHandleError(EngineError, RuntimeError): ...
class BadIndexError(EngineError, IndexError): ...
class BadParamError(EngineError, ValueError): ...
class LifecycleError(EngineError, RuntimeError): ...
class HotStartError(EngineError, RuntimeError): ...
class PluginError(EngineError, RuntimeError): ...
class FileError(EngineError, IOError): ...
class ParseError(EngineError, ValueError): ...
class NumericalError(EngineError, RuntimeError): ...
class CRSError(EngineError, ValueError): ...
class DependencyError(EngineError, RuntimeError): ...
class StaleObjectError(LifecycleError):
    def __init__(self, message: str = ...) -> None: ...


def raise_for_code(code: int, message: Optional[str] = ...) -> None: ...
