"""Type stubs for :mod:`openswmm.engine._infrastructure`."""

from collections.abc import Iterator
from typing import List, Tuple, Union

from ._enums import LidType
from ._solver import Solver


_Key = Union[int, str]


class Transects:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def add(self, transect_id: str) -> int: ...
    def set_roughness(
        self, idx: int, n_left: float, n_right: float, n_channel: float,
    ) -> None: ...
    def add_station(self, idx: int, station: float, elevation: float) -> None: ...
    def get_index(self, transect_id: str) -> int: ...
    def get_id(self, idx: int) -> str: ...
    def __iter__(self) -> Iterator[str]: ...
    def __contains__(self, key: object) -> bool: ...
    def remove(self, key: _Key) -> None: ...
    def rename(self, key: _Key, new_id: str) -> None: ...
    def station_count(self, idx: int) -> int: ...
    def get_station(self, idx: int, station_idx: int) -> Tuple[float, float]: ...
    def stations(self, idx: int) -> List[Tuple[float, float]]: ...
    def clear_stations(self, idx: int) -> None: ...
    def get_roughness(self, idx: int) -> Tuple[float, float, float]: ...
    def get_bank_stations(self, idx: int) -> Tuple[float, float]: ...
    def set_bank_stations(self, idx: int, left: float, right: float) -> None: ...
    def get_encroachment_stations(self, idx: int) -> Tuple[float, float]: ...
    def set_encroachment_stations(self, idx: int, left: float, right: float) -> None: ...
    def get_modifiers(self, idx: int) -> Tuple[float, float, float]: ...
    def set_modifiers(
        self, idx: int, n_factor: float, x_factor: float, y_factor: float,
    ) -> None: ...
    def get_comments(self, idx: int) -> str: ...
    def set_comments(self, idx: int, text: str) -> None: ...


class Streets:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def add(self, street_id: str) -> int: ...
    def get_index(self, street_id: str) -> int: ...
    def get_id(self, idx: int) -> str: ...
    def __iter__(self) -> Iterator[str]: ...
    def __contains__(self, key: object) -> bool: ...
    def set_params(
        self, idx: int, *,
        t_crown: float, h_curb: float, sx: float, n_road: float,
        gutter_depres: float = ..., gutter_width: float = ...,
        sides: int = ...,
        back_width: float = ..., back_slope: float = ..., back_n: float = ...,
    ) -> None: ...
    def get_params(self, idx: int) -> dict[str, float]:
        """Read back a street cross-section's geometric parameters.

        @return: Keys ``t_crown``, ``h_curb``, ``sx``, ``n_road``,
            ``gutter_depres``, ``gutter_width``, ``sides``, ``back_width``,
            ``back_slope``, ``back_n`` (the inverse of L{set_params}).
        @rtype: dict[str, float]
        """
        ...


class Inlets:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def add(self, inlet_id: str, inlet_type: str) -> int: ...
    def get_index(self, inlet_id: str) -> int: ...
    def get_id(self, idx: int) -> str: ...
    def __iter__(self) -> Iterator[str]: ...
    def __contains__(self, key: object) -> bool: ...
    def set_params(
        self, idx: int, *,
        length: float = ..., width: float = ...,
        grate_type: str = ...,
        open_area: float = ..., splash_veloc: float = ...,
    ) -> None: ...
    def get_params(self, idx: int) -> dict[str, float | str]: ...
    def get_type(self, idx: int) -> str: ...


class LIDs:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def add(self, lid_id: str, lid_type: LidType) -> int: ...
    def get_index(self, lid_id: str) -> int: ...
    def get_id(self, idx: int) -> str: ...
    def __iter__(self) -> Iterator[str]: ...
    def __contains__(self, key: object) -> bool: ...
    def set_surface(
        self, idx: int, *, storage: float, roughness: float, slope: float,
    ) -> None: ...
    def set_soil(
        self, idx: int, *,
        thick: float, porosity: float, fc: float,
        wp: float, ksat: float, kslope: float,
    ) -> None: ...
    def set_storage(
        self, idx: int, *, thick: float, void_frac: float, ksat: float,
    ) -> None: ...
    def set_drain(
        self, idx: int, *, coeff: float, expon: float, offset: float,
    ) -> None: ...
    def set_pavement(
        self, idx: int, *,
        thick: float, void_ratio: float, frac_imperv: float, ksat: float,
        clog_factor: float = ..., regen_days: float = ...,
    ) -> None: ...
    def set_drainmat(
        self, idx: int, *, thick: float, void_frac: float, roughness: float,
    ) -> None: ...
    def get_type(self, idx: int) -> int: ...
    def get_surface(self, idx: int) -> dict[str, float]: ...
    def get_soil(self, idx: int) -> dict[str, float]: ...
    def get_storage(self, idx: int) -> dict[str, float]: ...
    def get_drain(self, idx: int) -> dict[str, float]: ...
    def get_pavement(self, idx: int) -> dict[str, float]: ...
    def get_drainmat(self, idx: int) -> dict[str, float]: ...
    def usage_add(
        self, subcatchment: _Key, lid: int, *,
        number: int, area: float, width: float,
        init_sat: float = ..., from_imperv: float = ...,
    ) -> None: ...
    def usage_count(self) -> int: ...
    def usage_get(self, usage_idx: int) -> dict[str, float | int]: ...
    def usage_remove(self, usage_idx: int) -> None: ...


class Infrastructure:
    def __init__(self, solver: Solver) -> None: ...

    transects: Transects
    streets: Streets
    inlets: Inlets
    lids: LIDs
