"""Type stubs for :mod:`openswmm.engine._pollutants`."""

from collections.abc import Iterator
from typing import Optional, Tuple, Union

from ._enums import ConcentrationUnits
from ._solver import Solver


_Key = Union[int, str]


class Pollutant:
    id: str
    index: int
    solver: Solver
    units: ConcentrationUnits
    kdecay: float
    mwt: float
    rain_conc: float
    gw_conc: float
    init_conc: float
    rdii_conc: float
    dwf_conc: float
    snow_only: bool
    co_pollutant: Optional[Tuple["Pollutant", float]]

    def __init__(self, solver: Solver, index: int) -> None: ...
    def set_co_pollutant(self, co: Union["Pollutant", _Key], fraction: float) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...


class Pollutants:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Pollutant]: ...
    def __getitem__(self, key: _Key) -> Pollutant: ...
    def __contains__(self, key: object) -> bool: ...
    def get_index(self, pollut_id: str) -> int: ...
    def get_id(self, idx: int) -> str: ...
    def add(self, pollut_id: str, units: ConcentrationUnits = ...) -> Pollutant: ...
    def set_node_quality(self, node: _Key, pollutant: _Key, conc: float) -> None: ...
    def set_link_quality(self, link: _Key, pollutant: _Key, conc: float) -> None: ...
