"""Type stubs for :mod:`openswmm.engine._quality`."""

from collections.abc import Iterator
from typing import Dict, Union

from ._enums import BuildupFunc, WashoffFunc
from ._solver import Solver


_Key = Union[int, str]


class Landuse:
    id: str
    index: int
    sweep_interval: float
    sweep_removal: float

    def __init__(self, solver: Solver, index: int) -> None: ...


class Landuses:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Landuse]: ...
    def __getitem__(self, key: _Key) -> Landuse: ...
    def __contains__(self, key: object) -> bool: ...
    def get_index(self, landuse_id: str) -> int: ...
    def get_id(self, idx: int) -> str: ...
    def add(self, landuse_id: str) -> Landuse: ...


class Quality:
    def __init__(self, solver: Solver) -> None: ...

    landuses: Landuses

    def set_buildup(
        self, landuse: _Key, pollutant: _Key, *,
        func: BuildupFunc, c1: float, c2: float, c3: float, normalizer: int = ...,
    ) -> None: ...
    def get_buildup(self, landuse: _Key, pollutant: _Key) -> Dict[str, object]: ...

    def set_washoff(
        self, landuse: _Key, pollutant: _Key, *,
        func: WashoffFunc, coeff: float, expon: float,
        sweep_effic: float = ..., bmp_effic: float = ...,
    ) -> None: ...
    def get_washoff(self, landuse: _Key, pollutant: _Key) -> Dict[str, object]: ...

    def set_treatment(self, node: _Key, pollutant: _Key, expression: str) -> None: ...
    def get_treatment(self, node: _Key, pollutant: _Key) -> str: ...
    def clear_treatment(self, node: _Key, pollutant: _Key) -> None: ...
