"""Type stubs for :mod:`openswmm.engine._spatial`."""

from typing import Any, Tuple, Union

import numpy as np
from numpy.typing import NDArray

from ._solver import Solver


_Key = Union[int, str]


class Spatial:
    def __init__(self, solver: Solver) -> None: ...

    @property
    def crs(self) -> str:
        """Coordinate reference system (EPSG token, WKT, or proj string).
        Reading a model with no CRS raises :class:`CRSError`; assigning sets it."""
        ...
    @crs.setter
    def crs(self, value: str) -> None: ...

    def node_coord(self, node: _Key) -> Tuple[float, float]: ...
    def set_node_coord(self, node: _Key, x: float, y: float) -> None: ...
    def node_coords(self) -> NDArray[Any]: ...
    def set_node_coords(self, coords: NDArray[Any]) -> None: ...

    def link_coord(self, link: _Key) -> Tuple[float, float]: ...
    def set_link_coord(self, link: _Key, x: float, y: float) -> None: ...
    def link_vertices(self, link: _Key) -> NDArray[Any]: ...
    def set_link_vertices(self, link: _Key, vertices: NDArray[Any]) -> None: ...

    def subcatchment_coord(self, sub: _Key) -> Tuple[float, float]: ...
    def set_subcatchment_coord(self, sub: _Key, x: float, y: float) -> None: ...
    def subcatchment_polygon(self, sub: _Key) -> NDArray[Any]: ...
    def set_subcatchment_polygon(self, sub: _Key, polygon: NDArray[Any]) -> None: ...

    def gage_coord(self, gage: _Key) -> Tuple[float, float]: ...
    def set_gage_coord(self, gage: _Key, x: float, y: float) -> None: ...
