"""Type stubs for :mod:`openswmm.engine._tables`."""

from collections.abc import Iterator
from datetime import datetime
from typing import Any, Iterable, Union

import numpy as np
from numpy.typing import NDArray

from ._enums import PatternType, TableType
from ._solver import Solver


_Key = Union[int, str]


class _PointTable:
    id: str
    index: int
    solver: Solver

    def __init__(self, solver: Solver, index: int) -> None: ...
    def __len__(self) -> int: ...
    def add_point(self, x: float, y: float) -> None: ...
    def clear(self) -> None: ...
    def lookup(self, x: float) -> float: ...


class TimeSeries(_PointTable):
    points: NDArray[Any]  # structured: (time: datetime64[s], value: float64)

    def add(self, when: Union[datetime, float], value: float) -> None: ...


class Curve(_PointTable):
    points: NDArray[Any]  # float64, shape (n_points, 2)


class Tables:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_PointTable]: ...
    def __getitem__(self, key: _Key) -> _PointTable: ...
    def __contains__(self, key: object) -> bool: ...
    def get_index(self, table_id: str) -> int: ...
    def get_id(self, idx: int) -> str: ...
    def get_type(self, key: int | str) -> TableType:
        """The type of a table (time series vs. curve kind) as a L{TableType}.

        @param key: Table index or id.
        @rtype: L{TableType}
        """
        ...
    def add_timeseries(self, ts_id: str) -> TimeSeries: ...
    def add_curve(self, curve_id: str, curve_type: int = ...) -> Curve: ...
    def as_timeseries(self, key: _Key) -> TimeSeries: ...
    def as_curve(self, key: _Key) -> Curve: ...


class Pattern:
    index: int
    id: str
    solver: Solver
    type: PatternType
    factors: list[float]

    def __init__(self, solver: Solver, index: int) -> None: ...
    def set_factors(self, values: Iterable[float], type: PatternType = ...) -> None: ...


class Patterns:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Pattern]: ...
    def __getitem__(self, key: _Key) -> Pattern: ...
    def __contains__(self, key: object) -> bool: ...
    def get_index(self, pattern_id: str) -> int: ...
    def add(self, pattern_id: str, type: PatternType = ...) -> Pattern: ...
    def remove(self, key: _Key) -> None: ...
    def rename(self, key: _Key, new_id: str) -> None: ...
