"""
Type stub for the ``openswmm.solver._solver`` Cython extension module.

This file was originally generated by cyright and has been hand-edited to
carry complete epytext documentation for every public symbol.

:author: Caleb Buahin
:copyright: Copyright (c) 2026 Caleb Buahin
:license: MIT
"""

from enum import Enum
from typing import Any, Callable, List, Tuple, Union
from datetime import datetime


class SWMMObjects(Enum):
    """
    Enumeration of the top-level SWMM object categories.

    @ivar RAIN_GAGE: Rain gage object.
    @type RAIN_GAGE: int
    @ivar SUBCATCHMENT: Subcatchment object.
    @type SUBCATCHMENT: int
    @ivar NODE: Node object (junction, outfall, storage, or divider).
    @type NODE: int
    @ivar LINK: Link object (conduit, pump, orifice, weir, or outlet).
    @type LINK: int
    @ivar AQUIFER: Aquifer object.
    @type AQUIFER: int
    @ivar SNOWPACK: Snowpack object.
    @type SNOWPACK: int
    @ivar UNIT_HYDROGRAPH: Unit hydrograph object.
    @type UNIT_HYDROGRAPH: int
    @ivar LID: Low Impact Development (LID) control object.
    @type LID: int
    @ivar STREET: Street object.
    @type STREET: int
    @ivar INLET: Inlet object.
    @type INLET: int
    @ivar TRANSECT: Transect (irregular cross-section) object.
    @type TRANSECT: int
    @ivar XSECTION_SHAPE: Cross-section shape object.
    @type XSECTION_SHAPE: int
    @ivar CONTROL_RULE: Real-time control rule object.
    @type CONTROL_RULE: int
    @ivar POLLUTANT: Pollutant (water quality constituent) object.
    @type POLLUTANT: int
    @ivar LANDUSE: Land use object.
    @type LANDUSE: int
    @ivar CURVE: Hydraulic/hydrologic curve object.
    @type CURVE: int
    @ivar TIMESERIES: Time series object.
    @type TIMESERIES: int
    @ivar TIME_PATTERN: Time pattern object.
    @type TIME_PATTERN: int
    @ivar SYSTEM: System-level pseudo-object (one per simulation).
    @type SYSTEM: int
    """
    RAIN_GAGE = ...
    SUBCATCHMENT = ...
    NODE = ...
    LINK = ...
    AQUIFER = ...
    SNOWPACK = ...
    UNIT_HYDROGRAPH = ...
    LID = ...
    STREET = ...
    INLET = ...
    TRANSECT = ...
    XSECTION_SHAPE = ...
    CONTROL_RULE = ...
    POLLUTANT = ...
    LANDUSE = ...
    CURVE = ...
    TIMESERIES = ...
    TIME_PATTERN = ...
    SYSTEM = ...


class SWMMNodeTypes(Enum):
    """
    Enumeration of SWMM node subtypes.

    @ivar JUNCTION: Junction node — a simple connection point.
    @type JUNCTION: int
    @ivar OUTFALL: Outfall node — a terminal boundary condition node.
    @type OUTFALL: int
    @ivar STORAGE: Storage node — a node with storage volume.
    @type STORAGE: int
    @ivar DIVIDER: Flow divider node — splits flow among two outgoing links.
    @type DIVIDER: int
    """
    JUNCTION = ...
    OUTFALL = ...
    STORAGE = ...
    DIVIDER = ...


class SWMMRainGageProperties(Enum):
    """
    Enumeration of rain gage properties accessible via the SWMM API.

    @ivar GAGE_TOTAL_PRECIPITATION: Total precipitation depth at the gage (in or mm).
    @type GAGE_TOTAL_PRECIPITATION: int
    @ivar GAGE_RAINFALL: Rainfall intensity at the gage (in/hr or mm/hr).
    @type GAGE_RAINFALL: int
    @ivar GAGE_SNOWFALL: Snowfall intensity at the gage (in/hr or mm/hr).
    @type GAGE_SNOWFALL: int
    """
    GAGE_TOTAL_PRECIPITATION = ...
    GAGE_RAINFALL = ...
    GAGE_SNOWFALL = ...


class SWMMSubcatchmentProperties(Enum):
    """
    Enumeration of subcatchment properties accessible via the SWMM API.

    @ivar AREA: Subcatchment drainage area (acres or hectares).
    @type AREA: int
    @ivar RAINGAGE: Index of the rain gage assigned to the subcatchment.
    @type RAINGAGE: int
    @ivar RAINFALL: Current rainfall intensity (in/hr or mm/hr).
    @type RAINFALL: int
    @ivar EVAPORATION: Current evaporation rate (in/hr or mm/hr).
    @type EVAPORATION: int
    @ivar INFILTRATION: Current infiltration rate (in/hr or mm/hr).
    @type INFILTRATION: int
    @ivar RUNOFF: Current runoff flow rate (flow units).
    @type RUNOFF: int
    @ivar REPORT_FLAG: Flag controlling whether results are written to the report file.
    @type REPORT_FLAG: int
    @ivar WIDTH: Characteristic width of the subcatchment overland flow path (ft or m).
    @type WIDTH: int
    @ivar SLOPE: Average slope of the subcatchment (fraction).
    @type SLOPE: int
    @ivar CURB_LENGTH: Total curb length in the subcatchment (ft or m).
    @type CURB_LENGTH: int
    @ivar API_RAINFALL: Externally supplied rainfall intensity for API override (in/hr or mm/hr).
    @type API_RAINFALL: int
    @ivar API_SNOWFALL: Externally supplied snowfall intensity for API override (in/hr or mm/hr).
    @type API_SNOWFALL: int
    @ivar POLLUTANT_BUILDUP: Pollutant buildup on the subcatchment surface (mass/area).
    @type POLLUTANT_BUILDUP: int
    @ivar EXTERNAL_POLLUTANT_BUILDUP: Externally added pollutant buildup (mass/area).
    @type EXTERNAL_POLLUTANT_BUILDUP: int
    @ivar POLLUTANT_RUNOFF_CONCENTRATION: Pollutant concentration in runoff (mass/volume).
    @type POLLUTANT_RUNOFF_CONCENTRATION: int
    @ivar POLLUTANT_PONDED_CONCENTRATION: Pollutant concentration in ponded water (mass/volume).
    @type POLLUTANT_PONDED_CONCENTRATION: int
    @ivar POLLUTANT_TOTAL_LOAD: Total pollutant load washed off (mass).
    @type POLLUTANT_TOTAL_LOAD: int
    """
    AREA = ...
    RAINGAGE = ...
    RAINFALL = ...
    EVAPORATION = ...
    INFILTRATION = ...
    RUNOFF = ...
    REPORT_FLAG = ...
    WIDTH = ...
    SLOPE = ...
    CURB_LENGTH = ...
    API_RAINFALL = ...
    API_SNOWFALL = ...
    POLLUTANT_BUILDUP = ...
    EXTERNAL_POLLUTANT_BUILDUP = ...
    POLLUTANT_RUNOFF_CONCENTRATION = ...
    POLLUTANT_PONDED_CONCENTRATION = ...
    POLLUTANT_TOTAL_LOAD = ...


class SWMMNodeProperties(Enum):
    """
    Enumeration of node properties accessible via the SWMM API.

    @ivar TYPE: Node subtype code (see C{SWMMNodeTypes}).
    @type TYPE: int
    @ivar INVERT_ELEVATION: Node invert elevation above datum (ft or m).
    @type INVERT_ELEVATION: int
    @ivar MAX_DEPTH: Maximum node depth (ft or m).
    @type MAX_DEPTH: int
    @ivar DEPTH: Current water depth above invert (ft or m).
    @type DEPTH: int
    @ivar HYDRAULIC_HEAD: Current hydraulic head (ft or m above datum).
    @type HYDRAULIC_HEAD: int
    @ivar VOLUME: Current volume of water stored at the node (ft3 or m3).
    @type VOLUME: int
    @ivar LATERAL_INFLOW: Current lateral inflow rate (flow units).
    @type LATERAL_INFLOW: int
    @ivar TOTAL_INFLOW: Current total inflow rate (flow units).
    @type TOTAL_INFLOW: int
    @ivar FLOODING: Current flooding (overflow) rate (flow units).
    @type FLOODING: int
    @ivar REPORT_FLAG: Flag controlling whether results are written to the report file.
    @type REPORT_FLAG: int
    @ivar SURCHARGE_DEPTH: Current surcharge depth above the node crown (ft or m).
    @type SURCHARGE_DEPTH: int
    @ivar PONDING_AREA: Surface area used for ponded water storage (ft2 or m2).
    @type PONDING_AREA: int
    @ivar INITIAL_DEPTH: Initial water depth at the start of the simulation (ft or m).
    @type INITIAL_DEPTH: int
    @ivar POLLUTANT_CONCENTRATION: Pollutant concentration at the node (mass/volume).
        Use C{sub_index} to select individual pollutants.
    @type POLLUTANT_CONCENTRATION: int
    @ivar POLLUTANT_LATERAL_MASS_FLUX: Lateral pollutant mass flux entering the node (mass/time).
        Use C{sub_index} to select individual pollutants.
    @type POLLUTANT_LATERAL_MASS_FLUX: int
    """
    TYPE = ...
    INVERT_ELEVATION = ...
    MAX_DEPTH = ...
    DEPTH = ...
    HYDRAULIC_HEAD = ...
    VOLUME = ...
    LATERAL_INFLOW = ...
    TOTAL_INFLOW = ...
    FLOODING = ...
    REPORT_FLAG = ...
    SURCHARGE_DEPTH = ...
    PONDING_AREA = ...
    INITIAL_DEPTH = ...
    POLLUTANT_CONCENTRATION = ...
    POLLUTANT_LATERAL_MASS_FLUX = ...


class SWMMLinkProperties(Enum):
    """
    Enumeration of link properties accessible via the SWMM API.

    @ivar TYPE: Link subtype code (see C{SWMMLinkTypes}).
    @type TYPE: int
    @ivar START_NODE: Index of the upstream node.
    @type START_NODE: int
    @ivar END_NODE: Index of the downstream node.
    @type END_NODE: int
    @ivar LENGTH: Link length (ft or m).
    @type LENGTH: int
    @ivar SLOPE: Link slope (ft/ft or m/m).
    @type SLOPE: int
    @ivar FULL_DEPTH: Full (maximum) depth of the link cross-section (ft or m).
    @type FULL_DEPTH: int
    @ivar FULL_FLOW: Flow rate when the link is flowing full (flow units).
    @type FULL_FLOW: int
    @ivar SETTING: Current control setting (dimensionless fraction, 0-1).
    @type SETTING: int
    @ivar TIME_OPEN: Cumulative time the link control has been open (seconds).
    @type TIME_OPEN: int
    @ivar TIME_CLOSED: Cumulative time the link control has been closed (seconds).
    @type TIME_CLOSED: int
    @ivar FLOW: Current flow rate through the link (flow units).
    @type FLOW: int
    @ivar DEPTH: Current flow depth in the link (ft or m).
    @type DEPTH: int
    @ivar VELOCITY: Current flow velocity (ft/s or m/s).
    @type VELOCITY: int
    @ivar TOP_WIDTH: Current water surface top width (ft or m).
    @type TOP_WIDTH: int
    @ivar VOLUME: Current volume of water in the link (ft3 or m3).
    @type VOLUME: int
    @ivar CAPACITY: Current capacity utilisation as a fraction of full flow (0-1).
    @type CAPACITY: int
    @ivar REPORT_FLAG: Flag controlling whether results are written to the report file.
    @type REPORT_FLAG: int
    @ivar START_NODE_OFFSET: Offset of the link invert above the upstream node invert (ft or m).
    @type START_NODE_OFFSET: int
    @ivar END_NODE_OFFSET: Offset of the link invert above the downstream node invert (ft or m).
    @type END_NODE_OFFSET: int
    @ivar INITIAL_FLOW: Initial flow rate at the start of simulation (flow units).
    @type INITIAL_FLOW: int
    @ivar FLOW_LIMIT: Maximum allowable flow rate (flow units).
    @type FLOW_LIMIT: int
    @ivar INLET_LOSS: Minor loss coefficient at the link inlet (dimensionless).
    @type INLET_LOSS: int
    @ivar OUTLET_LOSS: Minor loss coefficient at the link outlet (dimensionless).
    @type OUTLET_LOSS: int
    @ivar AVERAGE_LOSS: Average minor loss coefficient (dimensionless).
    @type AVERAGE_LOSS: int
    @ivar SEEPAGE_RATE: Seepage loss rate per unit length (flow units/length).
    @type SEEPAGE_RATE: int
    @ivar HAS_FLAPGATE: Flag indicating presence of a flap gate (1 = yes, 0 = no).
    @type HAS_FLAPGATE: int
    @ivar POLLUTANT_CONCENTRATION: Pollutant concentration in the link flow (mass/volume).
        Use C{sub_index} to select individual pollutants.
    @type POLLUTANT_CONCENTRATION: int
    @ivar POLLUTANT_LOAD: Pollutant load transported through the link (mass/time).
        Use C{sub_index} to select individual pollutants.
    @type POLLUTANT_LOAD: int
    @ivar POLLUTANT_LATERAL_MASS_FLUX: Lateral pollutant mass flux entering the link (mass/time).
        Use C{sub_index} to select individual pollutants.
    @type POLLUTANT_LATERAL_MASS_FLUX: int
    """
    TYPE = ...
    START_NODE = ...
    END_NODE = ...
    LENGTH = ...
    SLOPE = ...
    FULL_DEPTH = ...
    FULL_FLOW = ...
    SETTING = ...
    TIME_OPEN = ...
    TIME_CLOSED = ...
    FLOW = ...
    DEPTH = ...
    VELOCITY = ...
    TOP_WIDTH = ...
    VOLUME = ...
    CAPACITY = ...
    REPORT_FLAG = ...
    START_NODE_OFFSET = ...
    END_NODE_OFFSET = ...
    INITIAL_FLOW = ...
    FLOW_LIMIT = ...
    INLET_LOSS = ...
    OUTLET_LOSS = ...
    AVERAGE_LOSS = ...
    SEEPAGE_RATE = ...
    HAS_FLAPGATE = ...
    POLLUTANT_CONCENTRATION = ...
    POLLUTANT_LOAD = ...
    POLLUTANT_LATERAL_MASS_FLUX = ...


class SWMMLinkTypes(Enum):
    """
    Enumeration of SWMM link subtypes.

    @ivar CONDUIT: Gravity-flow conduit link.
    @type CONDUIT: int
    @ivar PUMP: Pump link.
    @type PUMP: int
    @ivar ORIFICE: Orifice control link.
    @type ORIFICE: int
    @ivar WEIR: Weir control link.
    @type WEIR: int
    @ivar OUTLET: Outlet control link.
    @type OUTLET: int
    """
    CONDUIT = ...
    PUMP = ...
    ORIFICE = ...
    WEIR = ...
    OUTLET = ...


class SWMMSystemProperties(Enum):
    """
    Enumeration of system-level simulation properties accessible via the SWMM API.

    @ivar START_DATE: Simulation start date/time encoded as a SWMM double value.
    @type START_DATE: int
    @ivar CURRENT_DATE: Current simulation date/time encoded as a SWMM double value.
    @type CURRENT_DATE: int
    @ivar ELAPSED_TIME: Elapsed simulation time in decimal days.
    @type ELAPSED_TIME: int
    @ivar ROUTING_STEP: Hydraulic routing time step in seconds.
    @type ROUTING_STEP: int
    @ivar MAX_ROUTING_STEP: Maximum allowable routing time step in seconds.
    @type MAX_ROUTING_STEP: int
    @ivar REPORT_STEP: Reporting time step in seconds.
    @type REPORT_STEP: int
    @ivar TOTAL_STEPS: Total number of routing steps to be performed.
    @type TOTAL_STEPS: int
    @ivar NO_REPORT_FLAG: Flag suppressing output report generation (1 = suppress).
    @type NO_REPORT_FLAG: int
    @ivar FLOW_UNITS: Active flow unit code (see C{SWMMFlowUnits}).
    @type FLOW_UNITS: int
    @ivar END_DATE: Simulation end date/time encoded as a SWMM double value.
    @type END_DATE: int
    @ivar REPORT_START_DATE: Report start date/time encoded as a SWMM double value.
    @type REPORT_START_DATE: int
    @ivar UNIT_SYSTEM: Unit system code (0 = US customary, 1 = SI).
    @type UNIT_SYSTEM: int
    @ivar SURCHARGE_METHOD: Surcharge method code (0 = original SWMM, 1 = EXTRAN).
    @type SURCHARGE_METHOD: int
    @ivar ALLOW_PONDING: Flag enabling surface ponding at flooded nodes (1 = allow).
    @type ALLOW_PONDING: int
    @ivar INTERTIAL_DAMPING: Inertial damping option code.
    @type INTERTIAL_DAMPING: int
    @ivar NORMAL_FLOW_LIMITED: Normal flow limiting option code.
    @type NORMAL_FLOW_LIMITED: int
    @ivar SKIP_STEADY_STATE: Flag enabling steady-state skip detection (1 = skip).
    @type SKIP_STEADY_STATE: int
    @ivar IGNORE_RAINFALL: Flag suppressing rainfall processing (1 = ignore).
    @type IGNORE_RAINFALL: int
    @ivar IGNORE_RDII: Flag suppressing RDII processing (1 = ignore).
    @type IGNORE_RDII: int
    @ivar IGNORE_SNOWMELT: Flag suppressing snowmelt processing (1 = ignore).
    @type IGNORE_SNOWMELT: int
    @ivar IGNORE_GROUNDWATER: Flag suppressing groundwater processing (1 = ignore).
    @type IGNORE_GROUNDWATER: int
    @ivar IGNORE_ROUTING: Flag suppressing hydraulic routing (1 = ignore).
    @type IGNORE_ROUTING: int
    @ivar IGNORE_QUALITY: Flag suppressing water quality simulation (1 = ignore).
    @type IGNORE_QUALITY: int
    @ivar ERROR_CODE: Most recent internal SWMM error code (0 = no error).
    @type ERROR_CODE: int
    @ivar RULE_STEP: Control rule evaluation time step in seconds.
    @type RULE_STEP: int
    @ivar SWEEP_START: Street sweeping season start date (day of year).
    @type SWEEP_START: int
    @ivar SWEEP_END: Street sweeping season end date (day of year).
    @type SWEEP_END: int
    @ivar MAX_TRIALS: Maximum number of trials per routing time step.
    @type MAX_TRIALS: int
    @ivar NUM_THREADS: Number of parallel computation threads.
    @type NUM_THREADS: int
    @ivar MIN_ROUTE_STEP: Minimum allowable routing time step in seconds.
    @type MIN_ROUTE_STEP: int
    @ivar LENGTHENING_STEP: Conduit lengthening time step in seconds.
    @type LENGTHENING_STEP: int
    @ivar START_DRY_DAYS: Number of antecedent dry days before the simulation starts.
    @type START_DRY_DAYS: int
    @ivar COURANT_FACTOR: Courant number factor for time step adjustment.
    @type COURANT_FACTOR: int
    @ivar MIN_SURF_AREA: Minimum node surface area (ft2 or m2).
    @type MIN_SURF_AREA: int
    @ivar MIN_SLOPE: Minimum allowable conduit slope (ft/ft or m/m).
    @type MIN_SLOPE: int
    @ivar RUNOFF_ERROR: Allowable runoff continuity error (fraction).
    @type RUNOFF_ERROR: int
    @ivar FLOW_ERROR: Allowable flow routing continuity error (fraction).
    @type FLOW_ERROR: int
    @ivar QUAL_ERROR: Allowable water quality continuity error (fraction).
    @type QUAL_ERROR: int
    @ivar HEAD_TOL: Convergence tolerance for nodal heads (ft or m).
    @type HEAD_TOL: int
    @ivar SYS_FLOW_TOL: System flow balance tolerance (fraction).
    @type SYS_FLOW_TOL: int
    @ivar LAT_FLOW_TOL: Lateral flow balance tolerance (fraction).
    @type LAT_FLOW_TOL: int
    """
    START_DATE = ...
    CURRENT_DATE = ...
    ELAPSED_TIME = ...
    ROUTING_STEP = ...
    MAX_ROUTING_STEP = ...
    REPORT_STEP = ...
    TOTAL_STEPS = ...
    NO_REPORT_FLAG = ...
    FLOW_UNITS = ...
    END_DATE = ...
    REPORT_START_DATE = ...
    UNIT_SYSTEM = ...
    SURCHARGE_METHOD = ...
    ALLOW_PONDING = ...
    INTERTIAL_DAMPING = ...
    NORMAL_FLOW_LIMITED = ...
    SKIP_STEADY_STATE = ...
    IGNORE_RAINFALL = ...
    IGNORE_RDII = ...
    IGNORE_SNOWMELT = ...
    IGNORE_GROUNDWATER = ...
    IGNORE_ROUTING = ...
    IGNORE_QUALITY = ...
    ERROR_CODE = ...
    RULE_STEP = ...
    SWEEP_START = ...
    SWEEP_END = ...
    MAX_TRIALS = ...
    NUM_THREADS = ...
    MIN_ROUTE_STEP = ...
    LENGTHENING_STEP = ...
    START_DRY_DAYS = ...
    COURANT_FACTOR = ...
    MIN_SURF_AREA = ...
    MIN_SLOPE = ...
    RUNOFF_ERROR = ...
    FLOW_ERROR = ...
    QUAL_ERROR = ...
    HEAD_TOL = ...
    SYS_FLOW_TOL = ...
    LAT_FLOW_TOL = ...


class SWMMFlowUnits(Enum):
    """
    Enumeration of SWMM flow unit systems.

    @ivar CFS: Cubic feet per second (US customary).
    @type CFS: int
    @ivar GPM: Gallons per minute (US customary).
    @type GPM: int
    @ivar MGD: Million gallons per day (US customary).
    @type MGD: int
    @ivar CMS: Cubic meters per second (SI).
    @type CMS: int
    @ivar LPS: Liters per second (SI).
    @type LPS: int
    @ivar MLD: Million liters per day (SI).
    @type MLD: int
    """
    CFS = ...
    GPM = ...
    MGD = ...
    CMS = ...
    LPS = ...
    MLD = ...


class SWMMAPIErrors(Enum):
    """
    Enumeration of SWMM API error codes returned by C API functions.

    @ivar PROJECT_NOT_OPENED: The SWMM project has not been opened yet.
    @type PROJECT_NOT_OPENED: int
    @ivar SIMULATION_NOT_STARTED: The simulation has not been started yet.
    @type SIMULATION_NOT_STARTED: int
    @ivar SIMULATION_NOT_ENDED: The simulation has not been ended yet.
    @type SIMULATION_NOT_ENDED: int
    @ivar OBJECT_TYPE: Invalid or unrecognised SWMM object type code.
    @type OBJECT_TYPE: int
    @ivar OBJECT_INDEX: Object index is out of range.
    @type OBJECT_INDEX: int
    @ivar OBJECT_NAME: Object name was not found.
    @type OBJECT_NAME: int
    @ivar PROPERTY_TYPE: Invalid or unrecognised property type code.
    @type PROPERTY_TYPE: int
    @ivar PROPERTY_VALUE: Property value is out of the allowable range.
    @type PROPERTY_VALUE: int
    @ivar TIME_PERIOD: Requested time period is invalid.
    @type TIME_PERIOD: int
    @ivar HOTSTART_FILE_OPEN: Error opening the hot-start file.
    @type HOTSTART_FILE_OPEN: int
    @ivar HOTSTART_FILE_FORMAT: Hot-start file has an invalid format.
    @type HOTSTART_FILE_FORMAT: int
    @ivar SIMULATION_IS_RUNNING: Operation not permitted while simulation is running.
    @type SIMULATION_IS_RUNNING: int
    """
    PROJECT_NOT_OPENED = ...
    SIMULATION_NOT_STARTED = ...
    SIMULATION_NOT_ENDED = ...
    OBJECT_TYPE = ...
    OBJECT_INDEX = ...
    OBJECT_NAME = ...
    PROPERTY_TYPE = ...
    PROPERTY_VALUE = ...
    TIME_PERIOD = ...
    HOTSTART_FILE_OPEN = ...
    HOTSTART_FILE_FORMAT = ...
    SIMULATION_IS_RUNNING = ...


def run_solver(inp_file: str, rpt_file: str = None, out_file: str = None, swmm_progress_callback: Callable[[float], None] = ...) -> int:
    """
    Run a complete SWMM simulation from input file to output file.

    @param inp_file: Path to the SWMM input (``.inp``) file.
    @type inp_file: str
    @param rpt_file: Path for the report (``.rpt``) file.  If C{None}, the
        path is derived by replacing the ``.inp`` extension with ``.rpt``.
    @type rpt_file: str
    @param out_file: Path for the binary output (``.out``) file.  If C{None},
        the path is derived by replacing the ``.inp`` extension with ``.out``.
    @type out_file: str
    @param swmm_progress_callback: Optional callable invoked with a C{float}
        progress value (0.0–1.0) at regular intervals during the run.
    @type swmm_progress_callback: Callable[[float], None]
    @return: SWMM error code; C{0} indicates success.
    @rtype: int
    @raise SWMMSolverException: If the simulation fails with a non-zero error code.
    """
    ...


def decode_swmm_datetime(swmm_datetime: float) -> Any:
    """
    Decode a SWMM double-precision date value into a Python C{datetime} object.

    SWMM stores dates as the number of days elapsed since 30 December 1899
    (i.e., the OLE Automation date format).

    @param swmm_datetime: SWMM double-precision date value.
    @type swmm_datetime: float
    @return: Decoded C{datetime} object.
    @rtype: datetime
    """
    ...


def encode_swmm_datetime(dt: Any) -> float:
    """
    Encode a Python C{datetime} object as a SWMM double-precision date value.

    @param dt: The C{datetime} to encode.
    @type dt: datetime
    @return: SWMM double-precision date value (days since 30 December 1899).
    @rtype: float
    """
    ...


def version() -> int:
    """
    Return the SWMM engine version number.

    @return: Integer version number (e.g., C{51017} for SWMM 5.1.017).
    @rtype: int
    """
    ...


def get_error_message(error_code: int) -> str:
    """
    Return the human-readable message for a SWMM integer error code.

    @param error_code: SWMM error code (typically a negative integer or a
        positive API error code).
    @type error_code: int
    @return: Descriptive error message string.
    @rtype: str
    """
    ...


class SolverState(Enum):
    """
    Enumeration representing the lifecycle state of a C{Solver} instance.

    States transition in the order CREATED → OPEN → STARTED → FINISHED →
    ENDED → REPORTED → CLOSED, with CLOSED allowing a return to OPEN.

    @ivar CREATED: Solver has been instantiated but C{open()} has not been called.
    @type CREATED: int
    @ivar OPEN: The SWMM project has been opened successfully.
    @type OPEN: int
    @ivar STARTED: The simulation has been started (C{start()} called).
    @type STARTED: int
    @ivar FINISHED: All routing steps have completed (elapsed time reached zero).
    @type FINISHED: int
    @ivar ENDED: The simulation has been ended (C{end()} called).
    @type ENDED: int
    @ivar REPORTED: Results have been written to the report file (C{report()} called).
    @type REPORTED: int
    @ivar CLOSED: The SWMM project has been closed (C{close()} called).
    @type CLOSED: int
    """
    CREATED = ...
    OPEN = ...
    STARTED = ...
    FINISHED = ...
    ENDED = ...
    REPORTED = ...
    CLOSED = ...


class CallbackType(Enum):
    """
    Enumeration of lifecycle events for which callbacks can be registered.

    @ivar BEFORE_INITIALIZE: Fired before C{open()} is called during context-manager entry.
    @type BEFORE_INITIALIZE: int
    @ivar BEFORE_OPEN: Fired immediately before C{swmm_open()} is called.
    @type BEFORE_OPEN: int
    @ivar AFTER_OPEN: Fired immediately after C{swmm_open()} succeeds.
    @type AFTER_OPEN: int
    @ivar BEFORE_START: Fired immediately before C{swmm_start()} is called.
    @type BEFORE_START: int
    @ivar AFTER_START: Fired immediately after C{swmm_start()} succeeds.
    @type AFTER_START: int
    @ivar BEFORE_STEP: Fired before each stride step.
    @type BEFORE_STEP: int
    @ivar AFTER_STEP: Fired after each stride step.
    @type AFTER_STEP: int
    @ivar BEFORE_END: Fired immediately before C{swmm_end()} is called.
    @type BEFORE_END: int
    @ivar AFTER_END: Fired immediately after C{swmm_end()} succeeds.
    @type AFTER_END: int
    @ivar BEFORE_REPORT: Fired immediately before C{swmm_report()} is called.
    @type BEFORE_REPORT: int
    @ivar AFTER_REPORT: Fired immediately after C{swmm_report()} succeeds.
    @type AFTER_REPORT: int
    @ivar BEFORE_CLOSE: Fired immediately before C{swmm_close()} is called.
    @type BEFORE_CLOSE: int
    @ivar AFTER_CLOSE: Fired immediately after C{swmm_close()} succeeds.
    @type AFTER_CLOSE: int
    """
    BEFORE_INITIALIZE = ...
    BEFORE_OPEN = ...
    AFTER_OPEN = ...
    BEFORE_START = ...
    AFTER_START = ...
    BEFORE_STEP = ...
    AFTER_STEP = ...
    BEFORE_END = ...
    AFTER_END = ...
    BEFORE_REPORT = ...
    AFTER_REPORT = ...
    BEFORE_CLOSE = ...
    AFTER_CLOSE = ...


class SWMMSolverException(Exception):
    """
    Exception raised when a SWMM solver operation fails.

    @param message: Human-readable description of the failure.
    @type message: str
    """
    def __init__(self, message: str) -> None:
        """
        Initialise the exception with a descriptive error message.

        @param message: Human-readable description of the failure.
        @type message: str
        """
        ...


class Solver:
    """
    High-level interface to the SWMM engine for step-by-step or batch simulation.

    Wraps the SWMM C API (C{swmm_open}, C{swmm_start}, C{swmm_stride},
    C{swmm_end}, C{swmm_report}, C{swmm_close}) and provides property-based
    access to simulation parameters, lifecycle callbacks, and progress reporting.

    Use as a context manager for automatic lifecycle management::

        with Solver('model.inp') as solver:
            for elapsed, current_dt in solver:
                print(current_dt)

    Or exercise full manual control::

        solver = Solver('model.inp')
        solver.open()
        solver.start()
        while True:
            elapsed, dt = solver.step()
            if elapsed <= 0:
                break
        solver.end()
        solver.report()
        solver.close()

    @param inp_file: Path to the SWMM input (``.inp``) file.
    @type inp_file: str
    @param rpt_file: Path for the report (``.rpt``) file.  If C{None}, the
        path is derived by replacing the ``.inp`` extension with ``.rpt``.
    @type rpt_file: str
    @param out_file: Path for the binary output (``.out``) file.  If C{None},
        the path is derived by replacing the ``.inp`` extension with ``.out``.
    @type out_file: str
    @param stride_step: Default number of seconds to advance per C{step()} call.
        Defaults to C{300} (5 minutes).
    @type stride_step: int
    @param save_results: Whether to save results to the output file.
        Defaults to C{True}.
    @type save_results: bool
    """

    def __init__(
        self,
        inp_file: str,
        rpt_file: str = None,
        out_file: str = None,
        stride_step: int = 300,
        save_results: bool = True
    ):
        """
        Construct a new C{Solver} instance without opening the SWMM project.

        The SWMM project is not opened until C{open()} or C{initialize()} is
        called (or the instance is used as a context manager).

        @param inp_file: Path to the SWMM input (``.inp``) file.
        @type inp_file: str
        @param rpt_file: Path for the report (``.rpt``) file.  If C{None},
            derived from C{inp_file} by substituting the extension.
        @type rpt_file: str
        @param out_file: Path for the binary output (``.out``) file.  If C{None},
            derived from C{inp_file} by substituting the extension.
        @type out_file: str
        @param stride_step: Default stride duration in seconds for each
            C{step()} call.  Defaults to C{300}.
        @type stride_step: int
        @param save_results: Whether to save results to the binary output file.
            Defaults to C{True}.
        @type save_results: bool
        """
        ...

    # ====================================================================
    # File lifecycle
    # ====================================================================

    def __enter__(self):  # -> Self@Solver:
        """
        Enter the runtime context, opening and starting the SWMM project.

        Executes C{BEFORE_INITIALIZE} callbacks then calls C{open()}.

        @return: This C{Solver} instance.
        @rtype: Solver
        """
        ...

    def __exit__(self, exc_type, exc_value, traceback):  # -> None:
        """
        Exit the runtime context, finalising the simulation and releasing resources.

        Calls C{finalize()} regardless of whether an exception was raised.

        @param exc_type: Exception type, or C{None} if no exception was raised.
        @param exc_value: Exception instance, or C{None}.
        @param traceback: Traceback object, or C{None}.
        """
        ...

    def __iter__(self):  # -> Self@Solver:
        """
        Return this C{Solver} as its own iterator for use in C{for} loops.

        @return: This C{Solver} instance.
        @rtype: Solver
        """
        ...

    def __next__(self):  # -> tuple:
        """
        Advance the simulation by one stride step and return timing information.

        Raises C{StopIteration} when the simulation has finished (elapsed time
        returned by C{swmm_stride} is zero or negative).

        @return: 2-tuple of (elapsed simulation time in seconds, current datetime).
        @rtype: Tuple[float, datetime]
        @raise StopIteration: When the simulation has reached its end date.
        @raise SWMMSolverException: If the underlying stride call fails.
        """
        ...

    # ====================================================================
    # Timing
    # ====================================================================

    @property
    def start_datetime(self) -> datetime:
        """
        Simulation start date and time.

        @return: Start date/time decoded from the SWMM system property.
        @rtype: datetime
        """
        ...

    @start_datetime.setter
    def start_datetime(self, sim_start_datetime: datetime) -> None:
        """
        Set the simulation start date and time.

        @param sim_start_datetime: New start date/time for the simulation.
        @type sim_start_datetime: datetime
        @raise SWMMSolverException: If the underlying C API call fails.
        """
        ...

    @property
    def end_datetime(self) -> datetime:
        """
        Simulation end date and time.

        @return: End date/time decoded from the SWMM system property.
        @rtype: datetime
        """
        ...

    @end_datetime.setter
    def end_datetime(self, sim_end_datetime: datetime) -> None:
        """
        Set the simulation end date and time.

        @param sim_end_datetime: New end date/time for the simulation.
        @type sim_end_datetime: datetime
        @raise SWMMSolverException: If the underlying C API call fails.
        """
        ...

    @property
    def routing_step(self) -> float:
        """
        Hydraulic routing time step in seconds.

        @return: Current routing time step in seconds.
        @rtype: float
        """
        ...

    @routing_step.setter
    def routing_step(self, value: float) -> None:
        """
        Set the hydraulic routing time step.

        @param value: New routing time step in seconds.
        @type value: float
        @raise SWMMSolverException: If the underlying C API call fails.
        """
        ...

    @property
    def reporting_step(self) -> float:
        """
        Reporting time step in seconds.

        @return: Current reporting time step in seconds.
        @rtype: float
        """
        ...

    @reporting_step.setter
    def reporting_step(self, value: float) -> None:
        """
        Set the reporting time step.

        @param value: New reporting time step in seconds.
        @type value: float
        @raise SWMMSolverException: If the underlying C API call fails.
        """
        ...

    @property
    def report_start_datetime(self) -> datetime:
        """
        Report start date and time (results before this date are not written).

        @return: Report start date/time decoded from the SWMM system property.
        @rtype: datetime
        """
        ...

    @report_start_datetime.setter
    def report_start_datetime(self, report_start_datetime: datetime) -> None:
        """
        Set the report start date and time.

        @param report_start_datetime: New report start date/time.
        @type report_start_datetime: datetime
        @raise SWMMSolverException: If the underlying C API call fails.
        """
        ...

    @property
    def current_datetime(self) -> datetime:
        """
        Current simulation date and time (read-only during a running simulation).

        @return: Current simulation date/time decoded from the SWMM system property.
        @rtype: datetime
        """
        ...

    @property
    def stride_step(self) -> int:
        """
        Default stride duration used by C{step()} in seconds.

        @return: Current stride step value in seconds.
        @rtype: int
        """
        ...

    @stride_step.setter
    def stride_step(self, value: int):  # -> None:
        """
        Set the default stride duration used by C{step()}.

        @param value: New stride step value in seconds.
        @type value: int
        """
        ...

    # ====================================================================
    # Callbacks / diagnostics
    # ====================================================================

    @property
    def progress_callbacks_per_second(self) -> int:
        """
        Maximum number of times per wall-clock second that progress callbacks
        are invoked during C{execute()}.

        @return: Current progress callback rate (callbacks per second).
        @rtype: int
        """
        ...

    @progress_callbacks_per_second.setter
    def progress_callbacks_per_second(self, value: int) -> None:
        """
        Set the progress callback rate.

        Values less than C{1} are silently clamped to C{1}.

        @param value: Desired callback invocations per wall-clock second.
        @type value: int
        """
        ...

    @property
    def solver_state(self) -> SolverState:
        """
        Current lifecycle state of the solver.

        @return: A C{SolverState} member reflecting the current state.
        @rtype: SolverState
        """
        ...

    def add_callback(self, callback_type: CallbackType, callback: Callable[[Solver], None]) -> None:
        """
        Register a lifecycle callback for the given event type.

        The callback receives this C{Solver} instance as its sole argument and
        is called synchronously at the corresponding lifecycle event.

        @param callback_type: The lifecycle event to subscribe to.
        @type callback_type: CallbackType
        @param callback: A callable accepting a single C{Solver} argument.
        @type callback: Callable[[Solver], None]
        """
        ...

    def add_progress_callback(self, callback: Callable[[float], None]) -> None:
        """
        Register a progress callback invoked with simulation progress during C{execute()}.

        @param callback: A callable that accepts a single C{float} progress
            value in the range 0.0 (start) to 1.0 (completion).
        @type callback: Callable[[float], None]
        """
        ...

    # ====================================================================
    # Per-element accessors
    # ====================================================================

    def get_object_count(self, object_type: SWMMObjects) -> int:
        """
        Return the total count of objects of a given SWMM type.

        @param object_type: The SWMM object category to count.
        @type object_type: SWMMObjects
        @return: Number of objects of C{object_type} in the model.
        @rtype: int
        @raise SWMMSolverException: If the underlying C API call fails.
        """
        ...

    def get_object_name(self, object_type: SWMMObjects, index: int) -> str:
        """
        Return the name of a single SWMM object.

        @param object_type: The SWMM object category.
        @type object_type: SWMMObjects
        @param index: Zero-based index of the object within its category.
        @type index: int
        @return: Object name string as defined in the input file.
        @rtype: str
        @raise SWMMSolverException: If the underlying C API call fails.
        """
        ...

    def get_object_names(self, object_type: SWMMObjects) -> List[str]:
        """
        Return the names of all objects of a given SWMM type.

        @param object_type: The SWMM object category.
        @type object_type: SWMMObjects
        @return: Ordered list of object name strings (index matches object index).
        @rtype: List[str]
        @raise SWMMSolverException: If any underlying C API call fails.
        """
        ...

    def get_object_index(self, object_type: SWMMObjects, object_name: str) -> int:
        """
        Return the integer index of a named SWMM object.

        @param object_type: The SWMM object category.
        @type object_type: SWMMObjects
        @param object_name: Name of the object to look up.
        @type object_name: str
        @return: Zero-based index of the named object, or C{-1} if not found.
        @rtype: int
        """
        ...

    def set_value(self, object_type: SWMMObjects, property_type: Union[SWMMRainGageProperties, SWMMSubcatchmentProperties, SWMMNodeProperties, SWMMLinkProperties, SWMMSystemProperties], index: Union[int, str], value: float, sub_index: int = ...) -> None:
        """
        Set a property value on a SWMM object.

        @param object_type: The SWMM object category (e.g., C{SWMMObjects.NODE}).
        @type object_type: SWMMObjects
        @param property_type: The property to set (e.g., C{SWMMNodeProperties.DEPTH}).
        @type property_type: Union[SWMMRainGageProperties, SWMMSubcatchmentProperties, SWMMNodeProperties, SWMMLinkProperties, SWMMSystemProperties]
        @param index: Zero-based object index or object name string.
        @type index: Union[int, str]
        @param value: New value for the property in the active unit system.
        @type value: float
        @param sub_index: Secondary index for vector properties (e.g., pollutant
            index for C{POLLUTANT_CONCENTRATION}).  Defaults to C{-1} (not used).
        @type sub_index: int
        @raise SWMMSolverException: If the underlying C API call fails.
        """
        ...

    def get_value(self, object_type: SWMMObjects, property_type: Union[SWMMRainGageProperties, SWMMSubcatchmentProperties, SWMMNodeProperties, SWMMLinkProperties, SWMMSystemProperties], index: Union[int, str], sub_index: int = ...) -> float:
        """
        Get a property value from a SWMM object.

        @param object_type: The SWMM object category (e.g., C{SWMMObjects.NODE}).
        @type object_type: SWMMObjects
        @param property_type: The property to retrieve (e.g., C{SWMMNodeProperties.DEPTH}).
        @type property_type: Union[SWMMRainGageProperties, SWMMSubcatchmentProperties, SWMMNodeProperties, SWMMLinkProperties, SWMMSystemProperties]
        @param index: Zero-based object index or object name string.
        @type index: Union[int, str]
        @param sub_index: Secondary index for vector properties (e.g., pollutant
            index for C{POLLUTANT_CONCENTRATION}).  Defaults to C{-1} (not used).
        @type sub_index: int
        @return: Property value in the active unit system.
        @rtype: float
        @raise SWMMSolverException: If the underlying C API call fails.
        """
        ...

    # ====================================================================
    # Simulation control
    # ====================================================================

    def open(self) -> Any:
        """
        Open the SWMM project files and transition to the C{OPEN} state.

        Calls C{BEFORE_OPEN} callbacks, invokes C{swmm_open()}, then calls
        C{AFTER_OPEN} callbacks.  Has no effect if already in the C{OPEN} state.

        @return: C{None}
        @raise SWMMSolverException: If the solver is not in a valid state or
            C{swmm_open()} returns a non-zero error code.
        """
        ...

    def start(self) -> Any:
        """
        Start the simulation, transitioning from C{OPEN} to C{STARTED}.

        Calls C{BEFORE_START} callbacks, invokes C{swmm_start()}, then calls
        C{AFTER_START} callbacks.

        @return: C{None}
        @raise SWMMSolverException: If the solver is not in the C{OPEN} state or
            C{swmm_start()} returns a non-zero error code.
        """
        ...

    def initialize(self) -> Any:
        """
        Open and start the simulation in a single call.

        Equivalent to calling C{open()} followed by C{start()}.  Also fires
        the C{BEFORE_INITIALIZE} callbacks before opening.

        @return: C{None}
        @raise SWMMSolverException: If either C{open()} or C{start()} fails.
        """
        ...

    def step(self, steps: int = ...) -> tuple:
        """
        Advance the simulation by a fixed number of seconds (a "stride step").

        @param steps: Number of seconds to advance.  If greater than C{0},
            overrides the instance C{stride_step} for this call.  Defaults
            to C{0} (use the instance C{stride_step}).
        @type steps: int
        @return: 2-tuple of (elapsed simulation time remaining in seconds
            — C{0.0} when the simulation is complete, current simulation
            datetime).
        @rtype: Tuple[float, datetime]
        @raise SWMMSolverException: If C{swmm_stride()} returns a negative
            error code.
        """
        ...

    def end(self) -> Any:
        """
        End the simulation, transitioning to the C{ENDED} state.

        Calls C{BEFORE_END} callbacks, invokes C{swmm_end()}, then calls
        C{AFTER_END} callbacks.

        @return: C{None}
        @raise SWMMSolverException: If the solver is not in a valid state or
            C{swmm_end()} returns a non-zero error code.
        """
        ...

    def report(self) -> Any:
        """
        Write simulation results to the report file, transitioning to C{REPORTED}.

        Calls C{BEFORE_REPORT} callbacks, invokes C{swmm_report()}, then calls
        C{AFTER_REPORT} callbacks.

        @return: C{None}
        @raise SWMMSolverException: If the solver is not in the C{ENDED} state or
            C{swmm_report()} returns a non-zero error code.
        """
        ...

    def close(self) -> Any:
        """
        Close the SWMM project files, transitioning to the C{CLOSED} state.

        Calls C{BEFORE_CLOSE} callbacks, invokes C{swmm_close()}, then calls
        C{AFTER_CLOSE} callbacks.

        @return: C{None}
        @raise SWMMSolverException: If the solver is not in the C{REPORTED} state
            or C{swmm_close()} returns a non-zero error code.
        """
        ...

    def finalize(self) -> Any:
        """
        End, report, and close the simulation in a single call.

        Safely handles all intermediate states: calls C{end()}, C{report()}, and
        C{close()} as required based on the current C{solver_state}.  Has no effect
        if already in the C{CREATED} or C{CLOSED} state.

        @return: C{None}
        @raise SWMMSolverException: If any underlying lifecycle call fails.
        """
        ...

    def execute(self) -> Any:
        """
        Run the simulation to completion using the SWMM batch run API.

        Uses C{swmm_run_with_callback} if progress callbacks have been registered,
        otherwise uses C{swmm_run}.  Does not use the step-by-step lifecycle
        (C{open}/C{start}/C{step}/C{end}/C{report}/C{close}).

        @return: C{None}
        @raise SWMMSolverException: If the solver is not in a valid pre-run state
            or the run call fails.
        """
        ...

    # ====================================================================
    # Hot start
    # ====================================================================

    def use_hotstart(self, hotstart_file: str) -> Any:
        """
        Initialise the simulation state from a previously saved hot-start file.

        Must be called after C{open()} and before C{start()}.

        @param hotstart_file: Path to the hot-start (``.hst``) file to load.
        @type hotstart_file: str
        @return: C{None}
        @raise SWMMSolverException: If C{swmm_useHotStart()} returns a non-zero
            error code.
        """
        ...

    def save_hotstart(self, hotstart_file: str) -> Any:
        """
        Save the current simulation state to a hot-start file.

        @param hotstart_file: Path where the hot-start (``.hst``) file will be written.
        @type hotstart_file: str
        @return: C{None}
        @raise SWMMSolverException: If C{swmm_saveHotStart()} returns a non-zero
            error code.
        """
        ...

    # ====================================================================
    # Statistics / mass balance
    # ====================================================================

    def get_mass_balance_error(self) -> Tuple[float, float, float]:
        """
        Return the continuity error percentages for the completed simulation.

        Should be called after C{end()} and before C{close()}.

        @return: 3-tuple of (runoff continuity error %, flow routing continuity
            error %, water quality continuity error %).
        @rtype: Tuple[float, float, float]
        @raise SWMMSolverException: If the underlying C API call fails.
        """
        ...
