"""
This type stub file was generated by cyright.
"""
from __future__ import annotations

from enum import Enum
from typing import Any, Callable, List, Optional, Tuple, Union
from datetime import datetime

class SWMMObjects(Enum):
    """
    Enumeration of SWMM objects.

    :ivar RAIN_GAGE: Raingage object
    :type RAIN_GAGE: int
    :ivar SUBCATCHMENT: Subcatchment object
    :type SUBCATCHMENT: int 
    :ivar NODE: Node object
    :type NODE: int
    :ivar LINK: Link object
    :type LINK: int
    :ivar AQUIFER: Aquifer object
    :type AQUIFER: int
    :ivar SNOWPACK: Snowpack object
    :type SNOWPACK: int
    :ivar UNIT_HYDROGRAPH: Unit hydrograph object
    :type UNIT_HYDROGRAPH: int
    :ivar LID: LID object
    :type LID: int
    :ivar STREET: Street object
    :type STREET: int
    :ivar INLET: Inlet object
    :type INLET: int
    :ivar TRANSECT: Transect object
    :type TRANSECT: int
    :ivar XSECTION_SHAPE: Cross-section shape object
    :type XSECTION_SHAPE: int
    :ivar CONTROL_RULE: Control rule object
    :type CONTROL_RULE: int
    :ivar POLLUTANT: Pollutant object
    :type POLLUTANT: int
    :ivar LANDUSE: Land use object
    :type LANDUSE: int
    :ivar CURVE: Curve object
    :type CURVE: int
    :ivar TIMESERIES: Time series object
    :type TIMESERIES: int
    :ivar TIME_PATTERN: Time pattern object
    :type TIME_PATTERN: int
    :ivar SYSTEM: System object
    :type SYSTEM: int
    """
    RAIN_GAGE = ...
    SUBCATCHMENT = ...
    NODE = ...
    LINK = ...
    AQUIFER = ...
    SNOWPACK = ...
    UNIT_HYDROGRAPH = ...
    LID = ...
    STREET = ...
    INLET = ...
    TRANSECT = ...
    XSECTION_SHAPE = ...
    CONTROL_RULE = ...
    POLLUTANT = ...
    LANDUSE = ...
    CURVE = ...
    TIMESERIES = ...
    TIME_PATTERN = ...
    SYSTEM = ...


class SWMMNodeTypes(Enum):
    """
    Enumeration of SWMM node types.

    :ivar JUNCTION: Junction node
    :type JUNCTION: int
    :ivar OUTFALL: Outfall node
    :type OUTFALL: int
    :ivar STORAGE: Storage node
    :type STORAGE: int
    :ivar DIVIDER: Divider node
    :type DIVIDER: int
    """
    JUNCTION = ...
    OUTFALL = ...
    STORAGE = ...
    DIVIDER = ...


class SWMMRainGageProperties(Enum):
    """
    Enumeration of SWMM raingage properties.

    :ivar GAGE_TOTAL_PRECIPITATION: Total precipitation
    :type GAGE_TOTAL_PRECIPITATION: int
    :ivar GAGE_RAINFALL: Rainfall
    :type GAGE_RAINFALL: int
    :ivar GAGE_SNOWFALL: Snowfall
    :type GAGE_SNOWFALL: int
    :ivar GAGE_SCALEFACTOR: Rainfall scaling factor (dimensionless, > 0)
    :type GAGE_SCALEFACTOR: int
    """
    GAGE_TOTAL_PRECIPITATION = ...
    GAGE_RAINFALL = ...
    GAGE_SNOWFALL = ...
    GAGE_SCALEFACTOR = ...


class SWMMSubcatchmentProperties(Enum):
    """
    Enumeration of SWMM subcatchment properties.

    :ivar AREA: Area
    :type AREA: int
    :ivar RAINGAGE: Raingage
    :type RAINGAGE: int
    :ivar RAINFALL: Rainfall
    :type RAINFALL: int
    :ivar EVAPORATION: Evaporation
    :type EVAPORATION: int
    :ivar INFILTRATION: Infiltration
    :type INFILTRATION: int
    :ivar RUNOFF: Runoff
    :type RUNOFF: int
    :ivar REPORT_FLAG: Report flag
    :type REPORT_FLAG: int
    :ivar WIDTH: Width
    :type WIDTH: int
    :ivar SLOPE: Slope
    :type SLOPE: int
    :ivar CURB_LENGTH: Curb length
    :type CURB_LENGTH: int
    :ivar API_RAINFALL: API Rainfall
    :type API_RAINFALL: int
    :ivar API_SNOWFALL: API Snowfall
    :type API_SNOWFALL: int
    :ivar POLLUTANT_BUILDUP: Pollutant buildup
    :type POLLUTANT_BUILDUP: int
    :ivar EXTERNAL_POLLUTANT_BUILDUP: External pollutant buildup
    :type EXTERNAL_POLLUTANT_BUILDUP: int
    :ivar POLLUTANT_RUNOFF_CONCENTRATION: Pollutant runoff concentration
    :type POLLUTANT_RUNOFF_CONCENTRATION: int
    :ivar POLLUTANT_PONDED_CONCENTRATION: Pollutant ponded concentration
    :type POLLUTANT_PONDED_CONCENTRATION: int
    :ivar POLLUTANT_TOTAL_LOAD: Pollutant total load
    :type POLLUTANT_TOTAL_LOAD: int
    :ivar API_PET: API prescribed potential evapotranspiration rate
    :type API_PET: int
    """
    AREA = ...
    RAINGAGE = ...
    RAINFALL = ...
    EVAPORATION = ...
    INFILTRATION = ...
    RUNOFF = ...
    REPORT_FLAG = ...
    WIDTH = ...
    SLOPE = ...
    OUTLET_TYPE = ...
    OUTLET_INDEX = ...
    INFILTRATION_MODEL = ...
    FRACTION_IMPERVIOUS = ...
    SUB_AREA_ROUTE_TO = ...
    SUB_AREA_FRACTION_OUTLET = ...
    SUB_AREA_MANNINGS_N = ...
    SUB_AREA_FRACTION_AREA = ...
    SUB_AREA_DEPRESSION_STORAGE = ...
    SUB_AREA_INFLOW = ...
    SUB_AREA_RUNOFF = ...
    SUB_AREA_DEPTH = ...
    LID_UNITS_COUNT = ...
    LID_UNITS_PERV_AREA = ...
    LID_UNITS_FLOW_TO_PERV_AREA = ...
    LID_UNITS_DRAIN_FLOW = ...
    LID_UNIT_REPLICATES = ...
    LID_UNIT_AREA = ...
    LID_UNIT_FULL_WIDTH = ...
    LID_UNIT_BOTTOM_WIDTH = ...
    LID_UNIT_INIT_SATURATION = ...
    LID_UNIT_FROM_IMPERVIOUS = ...
    LID_UNIT_FROM_PERVIOUS = ...
    LID_UNIT_TO_PERVIOUS = ...
    LID_UNIT_RECEIVING_OUTLET_TYPE = ...
    LID_UNIT_RECEIVING_OUTLET_INDEX = ...
    LID_UNIT_SURFACE_DEPTH = ...
    LID_UNIT_SOIL_MOISTURE = ...
    LID_UNIT_GREEN_AMPT_CAPILLARY_SUCTION = ...
    LID_UNIT_GREEN_AMPT_SATURATED_CONDUCTIVITY = ...
    LID_UNIT_GREEN_AMPT_MAX_SOIL_MOISTURE_DEFICIT = ...
    CURB_LENGTH = ...
    API_RAINFALL = ...
    API_SNOWFALL = ...
    POLLUTANT_BUILDUP = ...
    EXTERNAL_POLLUTANT_BUILDUP = ...
    POLLUTANT_RUNOFF_CONCENTRATION = ...
    POLLUTANT_PONDED_CONCENTRATION = ...
    POLLUTANT_TOTAL_LOAD = ...
    API_PET = ...
    GW_MOISTURE = ...
    GW_LOWER_DEPTH = ...
    SNOW_SWE = ...
    SNOW_FW = ...
    SNOW_ATI = ...
    SNOW_COLDC = ...


class SWMMPollutantProperties(Enum):
    """
    Enumeration of SWMM pollutant properties (runtime-settable source
    concentrations in pollutant units).

    :ivar RAIN_CONCENTRATION: Rain (wet deposition) concentration
    :type RAIN_CONCENTRATION: int
    :ivar GW_CONCENTRATION: Groundwater inflow concentration
    :type GW_CONCENTRATION: int
    :ivar RDII_CONCENTRATION: RDII inflow concentration
    :type RDII_CONCENTRATION: int
    :ivar DWF_CONCENTRATION: Dry weather sanitary flow concentration
    :type DWF_CONCENTRATION: int
    :ivar KDECAY: First-order decay constant (1/day); live each step
    :ivar CO_POLLUTANT: Co-pollutant index (-1 = none)
    :ivar CO_FRACTION: Co-pollutant fraction (0-1)
    :ivar SNOW_ONLY: Buildup-only-under-snow flag (0/1)
    :ivar INIT_CONCENTRATION: Initial network concentration (pre-start only)
    """
    RAIN_CONCENTRATION = ...
    GW_CONCENTRATION = ...
    RDII_CONCENTRATION = ...
    DWF_CONCENTRATION = ...
    KDECAY = ...
    CO_POLLUTANT = ...
    CO_FRACTION = ...
    SNOW_ONLY = ...
    INIT_CONCENTRATION = ...


class SWMMPatternProperties(Enum):
    """
    Enumeration of SWMM time-pattern properties (runtime-settable
    multiplier factors). For ``FACTOR`` pass the 0-based factor position
    as the ``sub_index`` argument of ``set_value``/``get_value``.

    :ivar FACTOR: One multiplier factor (sub_index = factor position)
    :type FACTOR: int
    :ivar COUNT: Number of factors in the pattern (read-only)
    :type COUNT: int
    :ivar TYPE: Pattern type code (read-only): 0 monthly/1 daily/2 hourly/3 weekend
    :type TYPE: int
    """
    FACTOR = ...
    COUNT = ...
    TYPE = ...


class SWMMLandUseProperties(Enum):
    """
    Enumeration of SWMM land-use properties (runtime-settable street
    sweeping parameters).

    Buildup/washoff parameters are per land use and pollutant; pass the
    0-based pollutant index as the ``sub_index`` argument.

    :ivar SWEEP_INTERVAL: Street-sweeping interval (days)
    :type SWEEP_INTERVAL: int
    :ivar SWEEP_REMOVAL: Fraction of buildup available for sweeping (0-1)
    :type SWEEP_REMOVAL: int
    :ivar BUILDUP_FUNC: Buildup function type code (sub_index = pollutant)
    :ivar BUILDUP_COEFF1: Buildup coefficient c0 / max buildup
    :ivar BUILDUP_COEFF2: Buildup coefficient c1 / rate
    :ivar BUILDUP_COEFF3: Buildup coefficient c2 / exponent
    :ivar BUILDUP_NORMALIZER: Buildup normalizer: 0 area, 1 curb length
    :ivar WASHOFF_FUNC: Washoff function type code
    :ivar WASHOFF_COEFF: Washoff coefficient
    :ivar WASHOFF_EXPON: Washoff exponent
    :ivar WASHOFF_SWEEP_EFFIC: Washoff street-sweeping efficiency (0-1)
    :ivar WASHOFF_BMP_EFFIC: Washoff BMP efficiency (0-1)
    """
    SWEEP_INTERVAL = ...
    SWEEP_REMOVAL = ...
    BUILDUP_FUNC = ...
    BUILDUP_COEFF1 = ...
    BUILDUP_COEFF2 = ...
    BUILDUP_COEFF3 = ...
    BUILDUP_NORMALIZER = ...
    WASHOFF_FUNC = ...
    WASHOFF_COEFF = ...
    WASHOFF_EXPON = ...
    WASHOFF_SWEEP_EFFIC = ...
    WASHOFF_BMP_EFFIC = ...


class SWMMAquiferProperties(Enum):
    """
    Enumeration of SWMM aquifer properties (input-file units).

    The flux-coefficient properties (conductivity, slopes, evap/loss
    coefficients) are read live each step and are settable both before the
    simulation starts and while it is running; the structural /
    initial-condition properties are pre-start-only.

    :ivar POROSITY: Porosity (volumetric fraction, pre-start-only)
    :ivar WILTING_POINT: Wilting point (volumetric fraction, pre-start-only)
    :ivar FIELD_CAPACITY: Field capacity (volumetric fraction, pre-start-only)
    :ivar CONDUCTIVITY: Saturated hydraulic conductivity (in/hr or mm/hr)
    :ivar CONDUCT_SLOPE: Conductivity slope
    :ivar TENSION_SLOPE: Tension slope (ft or m)
    :ivar UPPER_EVAP_FRAC: Upper-zone evaporation fraction (0-1)
    :ivar LOWER_EVAP_DEPTH: Lower-zone evaporation depth (ft or m)
    :ivar LOWER_LOSS_COEFF: Lower-zone seepage-loss coefficient (in/hr or mm/hr)
    :ivar BOTTOM_ELEV: Aquifer bottom elevation (ft or m, pre-start-only)
    :ivar WATER_TABLE_ELEV: Initial water table elevation (ft or m, pre-start-only)
    :ivar UPPER_MOISTURE: Initial upper-zone moisture (volumetric fraction, pre-start-only)
    """
    POROSITY = ...
    WILTING_POINT = ...
    FIELD_CAPACITY = ...
    CONDUCTIVITY = ...
    CONDUCT_SLOPE = ...
    TENSION_SLOPE = ...
    UPPER_EVAP_FRAC = ...
    LOWER_EVAP_DEPTH = ...
    LOWER_LOSS_COEFF = ...
    BOTTOM_ELEV = ...
    WATER_TABLE_ELEV = ...
    UPPER_MOISTURE = ...


class SWMMNodeProperties(Enum):
    """
    Enumeration of SWMM node properties.

    :ivar TYPE: Node type
    :type TYPE: int
    :ivar INVERT_ELEVATION: Invert elevation
    :type INVERT_ELEVATION: int
    :ivar MAX_DEPTH: Maximum depth
    :type MAX_DEPTH: int
    :ivar DEPTH: Depth
    :type DEPTH: int
    :ivar HYDRAULIC_HEAD: Hydraulic head
    :type HYDRAULIC_HEAD: int
    :ivar VOLUME: Volume
    :type VOLUME: int
    :ivar LATERAL_INFLOW: Lateral inflow
    :type LATERAL_INFLOW: int
    :ivar TOTAL_INFLOW: Total inflow
    :type TOTAL_INFLOW: int
    :ivar FLOODING: Flooding
    :type FLOODING: int
    :ivar REPORT_FLAG: Report flag
    :type REPORT_FLAG: int
    :ivar SURCHARGE_DEPTH: Surcharge depth
    :type SURCHARGE_DEPTH: int
    :ivar PONDING_AREA: Ponding area
    :type PONDING_AREA: int
    :ivar INITIAL_DEPTH: Initial depth
    :type INITIAL_DEPTH: int
    :ivar POLLUTANT_CONCENTRATION: Pollutant concentration
    :type POLLUTANT_CONCENTRATION: int
    :ivar POLLUTANT_LATERAL_MASS_FLUX: Pollutant lateral mass flux
    :type POLLUTANT_LATERAL_MASS_FLUX: int
    :ivar OUTFLOW: Total outflow through downstream links
    :type OUTFLOW: int
    """
    TYPE = ...
    INVERT_ELEVATION = ...
    MAX_DEPTH = ...
    DEPTH = ...
    HYDRAULIC_HEAD = ...
    VOLUME = ...
    LATERAL_INFLOW = ...
    TOTAL_INFLOW = ...
    FLOODING = ...
    REPORT_FLAG = ...
    SURCHARGE_DEPTH = ...
    PONDING_AREA = ...
    INITIAL_DEPTH = ...
    POLLUTANT_CONCENTRATION = ...
    POLLUTANT_LATERAL_MASS_FLUX = ...
    OUTFLOW = ...


class SWMMLinkProperties(Enum):
    """
    Enumeration of SWMM link properties.

    :ivar TYPE: Link type
    :type TYPE: int
    :ivar START_NODE: Start node
    :type START_NODE: int
    :ivar END_NODE: End node
    :type END_NODE: int
    :ivar LENGTH: Length
    :type LENGTH: int
    :ivar SLOPE: Slope
    :type SLOPE: int
    :ivar FULL_DEPTH: Full depth
    :type FULL_DEPTH: int
    :ivar FULL_FLOW: Full flow
    :type FULL_FLOW: int
    :ivar SETTING: Setting
    :type SETTING: int
    :ivar TIME_OPEN: Time open
    :type TIME_OPEN: int
    :ivar TIME_CLOSED: Time closed
    :type TIME_CLOSED: int
    :ivar FLOW: Flow
    :type FLOW: int
    :ivar DEPTH: Depth
    :type DEPTH: int
    :ivar VELOCITY: Velocity
    :type VELOCITY: int
    :ivar TOP_WIDTH: Top width
    :type TOP_WIDTH: int
    :ivar REPORT_FLAG: Report flag
    :type REPORT_FLAG: int
    :ivar START_NODE_OFFSET: Start node offset
    :type START_NODE_OFFSET: int
    :ivar END_NODE_OFFSET: End node offset
    :type END_NODE_OFFSET: int
    :ivar INITIAL_FLOW: Initial flow
    :type INITIAL_FLOW: int
    :ivar FLOW_LIMIT: Flow limit
    :type FLOW_LIMIT: int
    :ivar INLET_LOSS: Inlet loss
    :type INLET_LOSS: int
    :ivar OUTLET_LOSS: Outlet loss
    :type OUTLET_LOSS: int
    :ivar AVERAGE_LOSS: Average loss
    :type AVERAGE_LOSS: int
    :ivar SEEPAGE_RATE: Seepage rate
    :type SEEPAGE_RATE: int
    :ivar HAS_FLAPGATE: Has flapgate
    :type HAS_FLAPGATE: int
    :ivar POLLUTANT_CONCENTRATION: Pollutant concentration
    :type POLLUTANT_CONCENTRATION: int
    :ivar POLLUTANT_LOAD: Pollutant load
    :type POLLUTANT_LOAD: int
    :ivar POLLUTANT_LATERAL_MASS_FLUX: Pollutant lateral mass flux
    :type POLLUTANT_LATERAL_MASS_FLUX: int
    """
    TYPE = ...
    START_NODE = ...
    END_NODE = ...
    LENGTH = ...
    SLOPE = ...
    FULL_DEPTH = ...
    FULL_FLOW = ...
    SETTING = ...
    TIME_OPEN = ...
    TIME_CLOSED = ...
    FLOW = ...
    DEPTH = ...
    VELOCITY = ...
    TOP_WIDTH = ...
    VOLUME = ...
    CAPACITY = ...
    REPORT_FLAG = ...
    START_NODE_OFFSET = ...
    END_NODE_OFFSET = ...
    INITIAL_FLOW = ...
    FLOW_LIMIT = ...
    INLET_LOSS = ...
    OUTLET_LOSS = ...
    AVERAGE_LOSS = ...
    SEEPAGE_RATE = ...
    HAS_FLAPGATE = ...
    POLLUTANT_CONCENTRATION = ...
    POLLUTANT_LOAD = ...
    POLLUTANT_LATERAL_MASS_FLUX = ...


class SWMMLinkTypes(Enum):
    """
    Enumeration of SWMM link types.

    :ivar CONDUIT: Conduit link
    :type CONDUIT: int
    :ivar PUMP: Pump link
    :type PUMP: int
    :ivar ORIFICE: Orifice link
    :type ORIFICE: int
    :ivar WEIR: Weir link
    :type WEIR: int
    :ivar OUTLET: Outlet link
    :type OUTLET: int
    """
    CONDUIT = ...
    PUMP = ...
    ORIFICE = ...
    WEIR = ...
    OUTLET = ...


class SWMMSystemProperties(Enum):
    """
    Enumeration of SWMM system properties.

    :ivar START_DATE: Start date for the simulation
    :type START_DATE: int
    :ivar CURRENT_DATE: Current date for the simulation
    :type CURRENT_DATE: int
    :ivar ELAPSED_TIME: Elapsed time for the simulation
    :type ELAPSED_TIME: int
    :ivar ROUTING_STEP: Routing time step
    :type ROUTING_STEP: int
    :ivar MAX_ROUTING_STEP: Maximum routing time step
    :type MAX_ROUTING_STEP: int
    :ivar REPORT_STEP: Report time step
    :type REPORT_STEP: int
    :ivar TOTAL_STEPS: Total number of steps
    :type TOTAL_STEPS: int
    :ivar NO_REPORT_FLAG: No report flag
    :type NO_REPORT_FLAG: int
    :ivar FLOW_UNITS: Flow units
    :type FLOW_UNITS: int
    :ivar END_DATE: End date for the simulation
    :type END_DATE: int
    :ivar REPORT_START_DATE: Report start date
    :type REPORT_START_DATE: int
    :ivar UNIT_SYSTEM: Unit system
    :type UNIT_SYSTEM: int
    :ivar SURCHARGE_METHOD: Surcharge method
    :type SURCHARGE_METHOD: int
    :ivar ALLOW_PONDING: Allow ponding
    :type ALLOW_PONDING: int
    :ivar INTERTIAL_DAMPING: Inertial damping
    :type INTERTIAL_DAMPING: int
    :ivar NORMAL_FLOW_LIMITED: Normal flow limited
    :type NORMAL_FLOW_LIMITED: int
    :ivar SKIP_STEADY_STATE: Skip steady state
    :type SKIP_STEADY_STATE: int
    :ivar IGNORE_RAINFALL: Ignore rainfall
    :type IGNORE_RAINFALL: int
    :ivar IGNORE_RDII: Ignore RDII
    :type IGNORE_RDII: int
    :ivar IGNORE_SNOWMELT: Ignore snowmelt
    :type IGNORE_SNOWMELT: int
    :ivar IGNORE_GROUNDWATER: Ignore groundwater
    :type IGNORE_GROUNDWATER: int
    :ivar IGNORE_ROUTING: Ignore routing
    :type IGNORE_ROUTING: int
    :ivar IGNORE_QUALITY: Ignore quality
    :type IGNORE_QUALITY: int
    :ivar RULE_STEP: Rule step
    :type RULE_STEP: int
    :ivar SWEEP_START: Sweep start
    :type SWEEP_START: int
    :ivar SWEEP_END: Sweep end
    :type SWEEP_END: int
    :ivar MAX_TRIALS: Maximum trials
    :type MAX_TRIALS: int
    :ivar NUM_THREADS: Number of threads
    :type NUM_THREADS: int
    :ivar MIN_ROUTE_STEP: Minimum routing step
    :type MIN_ROUTE_STEP: int
    :ivar LENGTHENING_STEP: Lengthening step
    :type LENGTHENING_STEP: int
    :ivar START_DRY_DAYS: Start dry days
    :type START_DRY_DAYS: int
    :ivar COURANT_FACTOR: Courant factor
    :type COURANT_FACTOR: int
    :ivar MIN_SURF_AREA: Minimum surface area
    :type MIN_SURF_AREA: int
    :ivar MIN_SLOPE: Minimum slope
    :type MIN_SLOPE: int
    :ivar RUNOFF_ERROR: Runoff error
    :type RUNOFF_ERROR: int
    :ivar FLOW_ERROR: Flow error
    :type FLOW_ERROR: int
    :ivar QUAL_ERROR: Quality error
    :type QUAL_ERROR: int
    :ivar HEAD_TOL: Head tolerance
    :type HEAD_TOL: int
    :ivar SYS_FLOW_TOL: System flow tolerance
    :type SYS_FLOW_TOL: int
    :ivar LAT_FLOW_TOL: Lateral flow tolerance
    :type LAT_FLOW_TOL: int
    :ivar EVAP_RATE: Current climate-derived evaporation rate (read-only)
    :type EVAP_RATE: int
    :ivar TEMPERATURE: Current air temperature (read-only)
    :type TEMPERATURE: int
    :ivar API_TEMPERATURE: API prescribed air temperature
    :type API_TEMPERATURE: int
    :ivar WIND_SPEED: Current wind speed (read-only)
    :type WIND_SPEED: int
    :ivar API_WIND_SPEED: API prescribed wind speed
    :type API_WIND_SPEED: int

    """
    START_DATE = ...
    CURRENT_DATE = ...
    ELAPSED_TIME = ...
    ROUTING_STEP = ...
    MAX_ROUTING_STEP = ...
    REPORT_STEP = ...
    TOTAL_STEPS = ...
    NO_REPORT_FLAG = ...
    FLOW_UNITS = ...
    END_DATE = ...
    REPORT_START_DATE = ...
    UNIT_SYSTEM = ...
    SURCHARGE_METHOD = ...
    ALLOW_PONDING = ...
    INTERTIAL_DAMPING = ...
    NORMAL_FLOW_LIMITED = ...
    SKIP_STEADY_STATE = ...
    IGNORE_RAINFALL = ...
    IGNORE_RDII = ...
    IGNORE_SNOWMELT = ...
    IGNORE_GROUNDWATER = ...
    IGNORE_ROUTING = ...
    IGNORE_QUALITY = ...
    ERROR_CODE = ...
    RULE_STEP = ...
    SWEEP_START = ...
    SWEEP_END = ...
    MAX_TRIALS = ...
    NUM_THREADS = ...
    MIN_ROUTE_STEP = ...
    LENGTHENING_STEP = ...
    START_DRY_DAYS = ...
    COURANT_FACTOR = ...
    MIN_SURF_AREA = ...
    MIN_SLOPE = ...
    RUNOFF_ERROR = ...
    FLOW_ERROR = ...
    QUAL_ERROR = ...
    HEAD_TOL = ...
    SYS_FLOW_TOL = ...
    LAT_FLOW_TOL = ...
    EVAP_RATE = ...
    TEMPERATURE = ...
    API_TEMPERATURE = ...
    WIND_SPEED = ...
    API_WIND_SPEED = ...
    API_EVAP = ...
    EVAP_DRY_ONLY = ...


class SWMMFlowUnits(Enum):
    """
    Enumeration of SWMM flow units.

    :ivar CFS: Cubic feet per second
    :type CFS: int
    :ivar GPM: Gallons per minute
    :type GPM: int
    :ivar MGD: Million gallons per day
    :type MGD: int
    :ivar CMS: Cubic meters per second
    :type CMS: int
    :ivar LPS: Liters per second
    :type LPS: int
    :ivar MLD: Million liters per day
    :type MLD: int
    """
    CFS = ...
    GPM = ...
    MGD = ...
    CMS = ...
    LPS = ...
    MLD = ...


class SWMMAPIErrors(Enum):
    """
    Enumeration of SWMM API errors.

    :ivar PROJECT_NOT_OPENED: Project not opened
    :type PROJECT_NOT_OPENED: int
    :ivar SIMULATION_NOT_STARTED: Simulation not started
    :type SIMULATION_NOT_STARTED: int
    :ivar SIMULATION_NOT_ENDED: Simulation not ended
    :type SIMULATION_NOT_ENDED: int    
    """
    PROJECT_NOT_OPENED = ...
    SIMULATION_NOT_STARTED = ...
    SIMULATION_NOT_ENDED = ...
    OBJECT_TYPE = ...
    OBJECT_INDEX = ...
    OBJECT_NAME = ...
    PROPERTY_TYPE = ...
    PROPERTY_VALUE = ...
    TIME_PERIOD = ...
    HOTSTART_FILE_OPEN = ...
    HOTSTART_FILE_FORMAT = ...
    SIMULATION_IS_RUNNING = ...


def run_solver(inp_file: str, rpt_file: Optional[str] = None, out_file: Optional[str] = None, swmm_progress_callback: Callable[[float], None] = ...) -> int:
    """
    Run a SWMM simulation with a progress callback.

    :param inp_file: Input file name
    :rtype inp_file: str
    :param rpt_file: Report file name
    :rtype rpt_file: str
    :param out_file: Output file name
    :rtype out_file: str
    :param swmm_progress_callback: Progress callback function
    :type swmm_progress_callback: callable
    :return: Error code from the underlying SWMM C API (0 on success,
        non-zero on failure). Callers should check the return value rather
        than relying on an exception.
    :rtype: int
    """
    ...

def decode_swmm_datetime(swmm_datetime: float) -> Any:
    """
    Decode a SWMM datetime into a datetime object.
    
    :param swmm_datetime: SWMM datetime float value
    :type swmm_datetime: float
    
    :return: datetime object
    :rtype: datetime
    """
    ...

def encode_swmm_datetime(dt: Any) -> float:
    """
    Encode a datetime object into a SWMM datetime float value.

    :param dt: datetime object
    :type dt: datetime
    :return: SWMM datetime float value
    :rtype: float
    """
    ...

def version() -> int:
    """
    Get the SWMM version.
    
    :return: SWMM version
    :rtype: str
    """
    ...

def get_error_message(error_code: int) -> str:
    """
    Get the error message for a SWMM error code.
    
    :param error_code: Error code
    :type error_code: int
    :return: Error message
    :rtype: str
    """
    ...

class SolverState(Enum):
    """
    An enumeration to represent the state of the solver.
    """
    CREATED = ...
    OPEN = ...
    STARTED = ...
    FINISHED = ...
    ENDED = ...
    REPORTED = ...
    CLOSED = ...


class CallbackType(Enum):
    """
    An enumeration to represent the type of callback.
    """
    BEFORE_INITIALIZE = ...
    BEFORE_OPEN = ...
    AFTER_OPEN = ...
    BEFORE_START = ...
    AFTER_START = ...
    BEFORE_STEP = ...
    AFTER_STEP = ...
    BEFORE_END = ...
    AFTER_END = ...
    BEFORE_REPORT = ...
    AFTER_REPORT = ...
    BEFORE_CLOSE = ...
    AFTER_CLOSE = ...


class SWMMSolverException(Exception):
    """
    Exception class for SWMM output file processing errors.
    """
    def __init__(self, message: str) -> None:
        """
        Constructor to initialize the exception message.

        :param message: Error message.
        :type message: str
        """
        ...
    


class Solver:

    
    def __init__(
        self,
        inp_file: str,
        rpt_file: Optional[str] = None,
        out_file: Optional[str] = None,
        stride_step: int = 300,
        save_results: bool = True
    ) -> None:
        """
        Constructor to create a new SWMM solver.

        :param inp_file: Input file name
        :param rpt_file: Report file name
        :param out_file: Output file name
        """
        ...

    """
    A class to represent a SWMM solver.
    """
    def __enter__(self) -> "Solver":
        """
        Enter method for context manager.
        """
        ...

    def __exit__(
        self,
        exc_type: Optional[type],
        exc_value: Optional[BaseException],
        traceback: Optional[object],
    ) -> None:
        """
        Exit method for context manager.
        """
        ...

    def __iter__(self) -> "Solver":
        """
        Iterator method for the solver.
        """
        ...
    
    def __next__(self) -> int:
        """
        Advance one step.

        :return: Error code from :py:meth:`step` (0 on success, non-zero on
            failure).
        :rtype: int
        :raises StopIteration: When the solver has finished.
        """
        ...
    
    @property
    def start_datetime(self) -> datetime:
        """
        Get the start date of the simulation.
        
        :return: Start date
        :rtype: datetime
        """
        ...
    
    @start_datetime.setter
    def start_datetime(self, sim_start_datetime: datetime) -> None:
        """
        Initialize the solver.
        
        :param sim_start_datetime: Start date of the simulation
        :return: Error code (0 if successful)
        """
        ...
    
    @property
    def end_datetime(self) -> datetime:
        """
        Get the end date of the simulation.
        
        :return: End date
        :rtype: datetime
        """
        ...
    
    @end_datetime.setter
    def end_datetime(self, sim_end_datetime: datetime) -> None:
        """
        Set the end date of the simulation.
        
        :param sim_end_datetime: End date of the simulation
        :return: Error code (0 if successful)
        """
        ...
    
    @property
    def routing_step(self) -> float:
        """
        Get the routing time step of the simulation in seconds.
        
        :return: Routing time step
        :rtype: double
        """
        ...
    
    @routing_step.setter
    def routing_step(self, value: float) -> None:
        """
        Set the routing time step of the simulation in seconds.
        
        :param value: Routing time step in seconds
        :type value: float
        """
        ...
    
    @property
    def reporting_step(self) -> float:
        """
        Get the reporting time step of the simulation in seconds.
        
        :return: Reporting time step
        :rtype: double
        """
        ...
    
    @reporting_step.setter
    def reporting_step(self, value: float) -> None:
        """
        Set the reporting time step of the simulation in seconds.
        
        :param value: Reporting time step in seconds
        :type value: float
        """
        ...
    
    @property
    def report_start_datetime(self) -> datetime:
        """
        Get the report start date of the simulation.
        
        :return: Report start date
        :rtype: datetime
        """
        ...
    
    @report_start_datetime.setter
    def report_start_datetime(self, report_start_datetime: datetime) -> None:
        """
        Set the report start date of the simulation.
        
        :param report_start_datetime: Report start date
        :type report_start_datetime: datetime
        """
        ...
    
    @property
    def current_datetime(self) -> datetime:
        """
        Get the current date of the simulation.
        
        :return: Current date
        :rtype: datetime
        """
        ...
    
    @property
    def progress_callbacks_per_second(self) -> int:
        """
        Get the number of progress callbacks per second.
        
        :return: Progress callbacks per second
        :rtype: int
        """
        ...
    
    @progress_callbacks_per_second.setter
    def progress_callbacks_per_second(self, value: int) -> None:
        """
        Set the number of progress callbacks per second.
        
        :param value: Progress callbacks per second
        :type value: int
        """
        ...
    
    def get_object_count(self, object_type: SWMMObjects) -> int:
        """
        Get the count of a SWMM object type.
        
        :param object_type: SWMM object type
        :type object_type: SWMMObjects
        :return: Object count
        :rtype: int
        """
        ...
    
    def get_object_name(self, object_type: SWMMObjects, index: int) -> str:
        """
        Get the name of a SWMM object.
        
        :param object_type: SWMM object type
        :type object_type: SWMMObjects
        :param index: Object index
        :type index: int
        :return: Object name
        :rtype: str
        """
        ...
    
    def get_object_names(self, object_type: SWMMObjects) -> List[str]:
        """
        Get the names of all SWMM objects of a given type.
        
        :param object_type: SWMM object type
        :type object_type: SWMMObjects
        :return: Object names
        :rtype: List[str]
        """
        ...
    
    def get_object_index(self, object_type: SWMMObjects, object_name: str) -> int:
        """
        Get the index of a SWMM object.
        
        :param object_type: SWMM object type
        :type object_type: SWMMObjects
        :param object_name: Object name
        :type object_name: str
        :return: Object index
        :rtype: int
        """
        ...
    
    def set_value(self, object_type: SWMMObjects, property_type: Union[SWMMRainGageProperties, SWMMSubcatchmentProperties, SWMMNodeProperties, SWMMLinkProperties, SWMMSystemProperties], index: Union[int, str], value: float, sub_index: int = ...) -> None:
        """
        Set a SWMM system property value.
        
        :param object_type: SWMM object type (e.g., SWMMObjects.NODE)
        :type object_type: SWMMObjects 
        :param property_type: SWMM system property type (e.g., SWMMSystemProperties.START_DATE)
        :type property_type: Union[SWMMRainGageProperties, SWMMSubcatchmentProperties, SWMMNodeProperties, SWMMLinkProperties, SWMMSystemProperties]
        :param index: Object index (e.g., 0, 'J1')
        :type index: int or str
        :param value: Property value (e.g., 10.0)
        :type value: double
        :param sub_index: Sub-index (e.g., 0) for properties with sub-indexes. For example pollutant index for POLLUTANT properties.
        :type sub_index: int
        """
        ...

    def set_treatment(self, node_index: Union[int, str], pollutant_index: int, expression: str) -> None:
        """
        Set (or replace) the treatment expression for a node/pollutant pair.

        Callable before the simulation starts or while it is running; a
        mid-run edit is evaluated from the next routing step on. A failed
        parse raises and leaves no treatment in place for the pair.

        :param node_index: Node index or name (e.g., 0, 'J1')
        :type node_index: int or str
        :param pollutant_index: Pollutant index (e.g., 0)
        :type pollutant_index: int
        :param expression: Treatment expression in input-file form, e.g. "R = 0.5" or "C = BOD * 0.2"
        :type expression: str
        """
        ...

    def clear_treatment(self, node_index: Union[int, str], pollutant_index: int) -> None:
        """
        Remove the treatment expression for a node/pollutant pair.

        Callable before the simulation starts or while it is running; zero
        removal applies from the next routing step on.

        :param node_index: Node index or name (e.g., 0, 'J1')
        :type node_index: int or str
        :param pollutant_index: Pollutant index (e.g., 0)
        :type pollutant_index: int
        """
        ...

    def set_lid_drain(self, lid_index: Union[int, str], coeff: float, expon: float, offset: float) -> None:
        """
        Set the underdrain flow parameters of a LID process at runtime.

        The drain parameters are read live each routing step, so a mid-run
        edit takes effect on the next step. Values use input-file units,
        matching the [LID_CONTROLS] DRAIN line.

        :param lid_index: LID process index or name (e.g., 0, 'RB1')
        :type lid_index: int or str
        :param coeff: Underdrain flow coefficient (in/hr or mm/hr)
        :type coeff: float
        :param expon: Underdrain head exponent
        :type expon: float
        :param offset: Offset height of the underdrain (in or mm)
        :type offset: float
        """
        ...

    def get_value(self, object_type: SWMMObjects, property_type: Union[SWMMRainGageProperties, SWMMSubcatchmentProperties, SWMMNodeProperties, SWMMLinkProperties, SWMMSystemProperties], index: Union[int, str], sub_index: int = ...) -> float:
        """
        Get a SWMM system property value.
        
        :param object_type: SWMM object type (e.g., SWMMObjects.NODE)
        :type object_type: SWMMObjects
        :param property_type: SWMM system property type (e.g., SWMMSystemProperties.START_DATE)
        :type property_type: Union[SWMMRainGageProperties, SWMMSubcatchmentProperties, SWMMNodeProperties, SWMMLinkProperties, SWMMSystemProperties]
        :param index: Object index (e.g., 0, 'J1')
        :type index: int or str
        :param sub_index: Sub-index (e.g., 0) for properties with sub-indexes. For example pollutant index for POLLUTANT properties.
        :type sub_index: int
        :return: Property value
        :rtype: double
        """
        ...
    
    @property
    def stride_step(self) -> int:
        """
        Get the stride step of the simulation.
        
        :return: Stride step
        :rtype: int
        """
        ...
    
    @stride_step.setter
    def stride_step(self, value: int) -> None:
        """
        Set the stride time step of the simulation.
        
        :param value: Stride step in seconds
        :type value: int
        """
        ...
    
    @property
    def solver_state(self) -> SolverState:
        """
        Get the state of the solver.
        
        :return: Solver state
        :rtype: SolverState
        """
        ...
    
    def add_callback(self, callback_type: CallbackType, callback: Callable[[Solver], None]) -> None:
        """
        Add a callback to the solver.
        
        :param callback_type: Type of callback
        :type callback_type: CallbackType
        :param callback: Callback function
        :type callback: callable
        """
        ...
    
    def add_progress_callback(self, callback: Callable[[float], None]) -> None:
        """
        Add a progress callback to the solver.
        
        :param callback: Progress callback function
        :type callback: callable
        """
        ...
    
    def open(self) -> int:
        """
        Open the SWMM solver by calling the open method in the SWMM API.

        :return: Error code (0 on success or no-op, non-zero on failure;
            -1 if called from an invalid solver state).
        :rtype: int
        """
        ...

    def start(self) -> int:
        """
        Start the SWMM solver.

        :return: Error code (0 on success or no-op, non-zero on failure;
            -1 if not in OPEN state).
        :rtype: int
        """
        ...

    def initialize(self) -> int:
        """
        Initialize the solver and start the simulation. Calls the open and
        start methods in the SWMM API.

        :return: Error code (0 on success, non-zero from the first failing
            sub-call).
        :rtype: int
        """
        ...

    def step(self, steps: int = ...) -> int:
        """
        Step a SWMM simulation forward.

        :param steps: Number of steps to run. Overrides internal stride
            step if greater than 0.
        :type steps: int
        :return: Error code (0 on success, non-zero on failure). The
            simulation transitions to the FINISHED state when complete;
            poll :py:attr:`solver_state` or read :py:attr:`current_datetime`
            for per-step data.
        :rtype: int
        """
        ...

    def end(self) -> int:
        """
        End the SWMM simulation.

        :return: Error code (0 on success or no-op, non-zero on failure;
            -1 if called from an invalid solver state).
        :rtype: int
        """
        ...

    def report(self) -> int:
        """
        Report the results of the SWMM simulation.

        :return: Error code (0 on success or no-op, non-zero on failure;
            -1 if not in ENDED state).
        :rtype: int
        """
        ...

    def close(self) -> int:
        """
        Close the solver.

        :return: Error code (0 on success or no-op, non-zero on failure;
            -1 if not in REPORTED state).
        :rtype: int
        """
        ...
    
    def finalize(self) -> Any:
        """
        Finalize the solver. Ends simulation, reports the results, and dispose objects.
        """
        ...
    
    def execute(self) -> Any:
        """
        Run the solver to completion.
        
        :return: Error code (0 if successful)
        """
        ...
    
    def use_hotstart(self, hotstart_file: str) -> Any:
        """
        Use a hotstart file.
        
        :param hotstart_file: Hotstart file name
        """
        ...
    
    def save_hotstart(self, hotstart_file: str) -> Any:
        """
        Save a hotstart file.
        
        :param hotstart_file: Hotstart file name
        """
        ...
    
    def get_mass_balance_error(self) -> Tuple[float, float, float]:
        """
        Get the mass balance error.

        :return: Mass balance error
        :rtype: Tuple[float, float, float]
        """
        ...

    def get_routing_totals(self) -> dict[str, float]:
        """
        Get system-level flow routing mass balance totals.

        :return: Dictionary with keys ``dw_inflow``, ``ww_inflow``,
            ``gw_inflow``, ``ii_inflow``, ``ex_inflow``, ``flooding``,
            ``outflow``, ``evap_loss``, ``seep_loss``, ``reacted``,
            ``init_storage``, ``final_storage``, ``pct_error``.
        :rtype: dict[str, float]
        """
        ...

    def get_runoff_totals(self) -> dict[str, float]:
        """
        Get system-level surface runoff mass balance totals.

        :return: Dictionary with keys ``rainfall``, ``evap``, ``infil``,
            ``runoff``, ``drains``, ``runon``, ``init_storage``,
            ``final_storage``, ``init_snow_cover``, ``final_snow_cover``,
            ``snow_removed``, ``pct_error``.
        :rtype: dict[str, float]
        """
        ...

    def get_node_statistics(self, index: Union[int, str]) -> dict[str, Any]:
        """Per-node post-simulation statistics."""
        ...

    def get_link_statistics(self, index: Union[int, str]) -> dict[str, Any]:
        """Per-link post-simulation statistics."""
        ...

    def get_pump_statistics(self, index: Union[int, str]) -> dict[str, Any]:
        """Per-pump post-simulation statistics."""
        ...

    def get_subcatchment_statistics(self, index: Union[int, str]) -> dict[str, Any]:
        """Per-subcatchment post-simulation statistics."""
        ...



