"""
Type stub for the ``openswmm.output._output`` Cython extension module.

This file was originally generated by cyright and has been hand-edited to
carry complete epytext documentation for every public symbol.

:author: Caleb Buahin
:copyright: Copyright (c) 2026 Caleb Buahin
:license: MIT
"""

from enum import Enum
from typing import Dict, List, Optional, Tuple, Union
from cpython.datetime import datetime


class UnitSystem(Enum):
    """
    Enumeration of the unit system used in the output file.

    @ivar US: US customary units.
    @type US: int
    @ivar SI: SI metric units.
    @type SI: int
    """
    US = ...
    SI = ...


class FlowUnits(Enum):
    """
    Enumeration of the flow units used in the simulation.

    @ivar CFS: Cubic feet per second.
    @type CFS: int
    @ivar GPM: Gallons per minute.
    @type GPM: int
    @ivar MGD: Million gallons per day.
    @type MGD: int
    @ivar CMS: Cubic meters per second.
    @type CMS: int
    @ivar LPS: Liters per second.
    @type LPS: int
    @ivar MLD: Million liters per day.
    @type MLD: int
    """
    CFS = ...
    GPM = ...
    MGD = ...
    CMS = ...
    LPS = ...
    MLD = ...


class ConcentrationUnits(Enum):
    """
    Enumeration of the concentration units used in the simulation.

    @ivar MG: Milligrams per liter (mg/L).
    @type MG: int
    @ivar UG: Micrograms per liter (ug/L).
    @type UG: int
    @ivar COUNT: Counts per liter (#/L).
    @type COUNT: int
    @ivar NONE: No concentration units (dimensionless).
    @type NONE: int
    """
    MG = ...
    UG = ...
    COUNT = ...
    NONE = ...


class ElementType(Enum):
    """
    Enumeration of the SWMM element types stored in an output file.

    @ivar SUBCATCHMENT: Subcatchment element.
    @type SUBCATCHMENT: int
    @ivar NODE: Node element (junction, outfall, storage, or divider).
    @type NODE: int
    @ivar LINK: Link element (conduit, pump, orifice, weir, or outlet).
    @type LINK: int
    @ivar SYSTEM: System-level pseudo-element (one per simulation).
    @type SYSTEM: int
    @ivar POLLUTANT: Pollutant element (water quality constituent).
    @type POLLUTANT: int
    """
    SUBCATCHMENT = ...
    NODE = ...
    LINK = ...
    SYSTEM = ...
    POLLUTANT = ...


class TimeAttribute(Enum):
    """
    Enumeration of the report-time meta-attributes stored in the output file.

    @ivar REPORT_STEP: Reporting time step size in seconds.
    @type REPORT_STEP: int
    @ivar NUM_PERIODS: Total number of reporting periods written to the file.
    @type NUM_PERIODS: int
    """
    REPORT_STEP = ...
    NUM_PERIODS = ...


class SubcatchAttribute(Enum):
    """
    Enumeration of the subcatchment result attributes recorded per reporting period.

    @ivar RAINFALL: Subcatchment rainfall rate (in/hr or mm/hr).
    @type RAINFALL: int
    @ivar SNOW_DEPTH: Subcatchment snow depth (in or mm).
    @type SNOW_DEPTH: int
    @ivar EVAPORATION_LOSS: Subcatchment evaporation loss rate (in/hr or mm/hr).
    @type EVAPORATION_LOSS: int
    @ivar INFILTRATION_LOSS: Subcatchment infiltration loss rate (in/hr or mm/hr).
    @type INFILTRATION_LOSS: int
    @ivar RUNOFF_RATE: Subcatchment surface runoff rate (flow units).
    @type RUNOFF_RATE: int
    @ivar GROUNDWATER_OUTFLOW: Subcatchment groundwater outflow rate (flow units).
    @type GROUNDWATER_OUTFLOW: int
    @ivar GROUNDWATER_TABLE_ELEVATION: Subcatchment groundwater table elevation (ft or m).
    @type GROUNDWATER_TABLE_ELEVATION: int
    @ivar SOIL_MOISTURE: Subcatchment unsaturated zone soil moisture content (dimensionless fraction).
    @type SOIL_MOISTURE: int
    @ivar POLLUTANT_CONCENTRATION: Subcatchment runoff pollutant concentration (mass/volume).
        Use C{sub_index} to select individual pollutants.
    @type POLLUTANT_CONCENTRATION: int
    """
    RAINFALL = ...
    SNOW_DEPTH = ...
    EVAPORATION_LOSS = ...
    INFILTRATION_LOSS = ...
    RUNOFF_RATE = ...
    GROUNDWATER_OUTFLOW = ...
    GROUNDWATER_TABLE_ELEVATION = ...
    SOIL_MOISTURE = ...
    POLLUTANT_CONCENTRATION = ...


class NodeAttribute(Enum):
    """
    Enumeration of the node result attributes recorded per reporting period.

    @ivar INVERT_DEPTH: Water depth above the node invert elevation (ft or m).
    @type INVERT_DEPTH: int
    @ivar HYDRAULIC_HEAD: Node hydraulic head (ft or m above datum).
    @type HYDRAULIC_HEAD: int
    @ivar STORED_VOLUME: Volume of water stored at the node (ft3 or m3).
    @type STORED_VOLUME: int
    @ivar LATERAL_INFLOW: Lateral (direct) inflow rate at the node (flow units).
    @type LATERAL_INFLOW: int
    @ivar TOTAL_INFLOW: Total inflow rate entering the node (flow units).
    @type TOTAL_INFLOW: int
    @ivar FLOODING_LOSSES: Flooding loss rate leaving the node (flow units).
    @type FLOODING_LOSSES: int
    @ivar POLLUTANT_CONCENTRATION: Node water quality pollutant concentration (mass/volume).
        Use C{sub_index} to select individual pollutants.
    @type POLLUTANT_CONCENTRATION: int
    """
    INVERT_DEPTH = ...
    HYDRAULIC_HEAD = ...
    STORED_VOLUME = ...
    LATERAL_INFLOW = ...
    TOTAL_INFLOW = ...
    FLOODING_LOSSES = ...
    POLLUTANT_CONCENTRATION = ...


class LinkAttribute(Enum):
    """
    Enumeration of the link result attributes recorded per reporting period.

    @ivar FLOW_RATE: Link flow rate (flow units).
    @type FLOW_RATE: int
    @ivar FLOW_DEPTH: Link flow depth (ft or m).
    @type FLOW_DEPTH: int
    @ivar FLOW_VELOCITY: Link flow velocity (ft/s or m/s).
    @type FLOW_VELOCITY: int
    @ivar FLOW_VOLUME: Link flow volume (ft3 or m3).
    @type FLOW_VOLUME: int
    @ivar CAPACITY: Link capacity as a fraction of full conduit depth (dimensionless, 0–1).
    @type CAPACITY: int
    @ivar POLLUTANT_CONCENTRATION: Link water quality pollutant concentration (mass/volume).
        Use C{sub_index} to select individual pollutants.
    @type POLLUTANT_CONCENTRATION: int
    """
    FLOW_RATE = ...
    FLOW_DEPTH = ...
    FLOW_VELOCITY = ...
    FLOW_VOLUME = ...
    CAPACITY = ...
    POLLUTANT_CONCENTRATION = ...


class SystemAttribute(Enum):
    """
    Enumeration of the system-level result attributes recorded per reporting period.

    @ivar AIR_TEMP: Air temperature (deg F or deg C).
    @type AIR_TEMP: int
    @ivar RAINFALL: System-wide rainfall intensity (in/hr or mm/hr).
    @type RAINFALL: int
    @ivar SNOW_DEPTH: System-wide snow depth (in or mm).
    @type SNOW_DEPTH: int
    @ivar EVAP_INFIL_LOSS: Combined evaporation and infiltration loss rate (in/day or mm/day).
    @type EVAP_INFIL_LOSS: int
    @ivar RUNOFF_FLOW: Total surface runoff flow rate (flow units).
    @type RUNOFF_FLOW: int
    @ivar DRY_WEATHER_INFLOW: Total dry weather inflow rate (flow units).
    @type DRY_WEATHER_INFLOW: int
    @ivar GROUNDWATER_INFLOW: Total groundwater inflow rate (flow units).
    @type GROUNDWATER_INFLOW: int
    @ivar RDII_INFLOW: Total Rainfall Derived Infiltration and Inflow rate (flow units).
    @type RDII_INFLOW: int
    @ivar DIRECT_INFLOW: Total direct inflow rate (flow units).
    @type DIRECT_INFLOW: int
    @ivar TOTAL_LATERAL_INFLOW: Sum of dry weather, groundwater, RDII, and direct inflows (flow units).
    @type TOTAL_LATERAL_INFLOW: int
    @ivar FLOOD_LOSSES: Total system-wide flooding loss rate (flow units).
    @type FLOOD_LOSSES: int
    @ivar OUTFALL_FLOWS: Total outfall discharge rate (flow units).
    @type OUTFALL_FLOWS: int
    @ivar VOLUME_STORED: Total volume stored in all storage nodes (ft3 or m3).
    @type VOLUME_STORED: int
    @ivar EVAPORATION_RATE: Actual evaporation rate (in/day or mm/day).
    @type EVAPORATION_RATE: int
    """
    AIR_TEMP = ...
    RAINFALL = ...
    SNOW_DEPTH = ...
    EVAP_INFIL_LOSS = ...
    RUNOFF_FLOW = ...
    DRY_WEATHER_INFLOW = ...
    GROUNDWATER_INFLOW = ...
    RDII_INFLOW = ...
    DIRECT_INFLOW = ...
    TOTAL_LATERAL_INFLOW = ...
    FLOOD_LOSSES = ...
    OUTFALL_FLOWS = ...
    VOLUME_STORED = ...
    EVAPORATION_RATE = ...


class SWMMOutputException(Exception):
    """
    Exception raised when an error occurs while reading a SWMM binary output file.

    @param message: Human-readable description of the error condition.
    @type message: str
    """
    def __init__(self, message: str) -> None:
        """
        Initialise the exception with a descriptive error message.

        @param message: Human-readable description of the error condition.
        @type message: str
        """
        ...


class Output:
    """
    Reader for the binary output file (``.out``) produced by a SWMM simulation.

    On construction the file is opened and key metadata (version, unit system,
    element counts, start date, and reporting periods) is read and cached.
    All subsequent accessors use the cached values or call the underlying C API
    as needed.  Use as a context manager to guarantee the file handle is closed::

        with Output('simulation.out') as out:
            ts = out.get_node_timeseries(0, NodeAttribute.INVERT_DEPTH)
            for dt, value in ts.items():
                print(dt, value)

    @cvar _output_file_handle: Internal C-level handle to the open SWMM output file.
    @cvar _version: SWMM version number recorded in the output-file header.
    @cvar _units: Raw integer array of unit codes
        (index 0 = unit system, index 1 = flow units, index 2+ = pollutant units).
    @cvar _flow_units: Cached integer code for the active flow-unit system.
    @cvar _output_size: Cached integer array of element counts indexed by
        C{ElementType} value (subcatchments, nodes, links, system, pollutants).
    @cvar _pollutant_units: Cached C{ConcentrationUnits} list, one entry per pollutant.
    @cvar _start_date: Simulation start date decoded from the output-file header.
    @cvar _report_step: Reporting time step in seconds.
    @cvar _num_periods: Total number of reporting periods stored in the file.
    @cvar _times: Pre-computed list of C{datetime} objects for every reporting period.

    @param output_file: Absolute or relative path to the SWMM ``.out`` file.
    @type output_file: str
    @raise FileNotFoundError: If no file exists at C{output_file}.
    @raise SWMMOutputException: If the SWMM output API cannot be initialised
        or the file header is invalid.
    """
    def __init__(self, output_file: str) -> None:
        """
        Open and parse the SWMM binary output file, caching all header metadata.

        @param output_file: Absolute or relative path to the SWMM ``.out`` file.
        @type output_file: str
        @raise FileNotFoundError: If no file exists at C{output_file}.
        @raise SWMMOutputException: If the SWMM output API initialisation or
            file-open call returns a non-zero error code.
        """
        ...

    # ====================================================================
    # File lifecycle
    # ====================================================================

    def __enter__(self):  # -> Self@Output:
        """
        Enter the runtime context; returns this C{Output} instance.

        @return: This C{Output} instance, ready for metadata and time-series access.
        @rtype: Output
        """
        ...

    def __exit__(self, exc_type, exc_value, traceback):  # -> None:
        """
        Exit the runtime context, releasing all C-level output file resources.

        Calls the internal close routine regardless of whether an exception
        was raised inside the C{with} block.

        @param exc_type: Exception type, or C{None} if no exception was raised.
        @param exc_value: Exception instance, or C{None}.
        @param traceback: Traceback object, or C{None}.
        """
        ...

    # ====================================================================
    # Metadata
    # ====================================================================

    @property
    def version(self) -> int:
        """
        SWMM engine version number recorded in the output file header.

        @return: Integer version number (e.g., C{51017} for SWMM 5.1.017).
        @rtype: int
        """
        ...

    @property
    def output_size(self) -> Dict[str, int]:
        """
        Element counts for each object category stored in the output file.

        @return: Dictionary with keys C{'subcatchments'}, C{'nodes'},
            C{'links'}, C{'system'}, and C{'pollutants'} mapped to their
            respective element counts.
        @rtype: Dict[str, int]
        """
        ...

    @property
    def units(self) -> Tuple[UnitSystem, FlowUnits, Optional[List[ConcentrationUnits]]]:
        """
        All unit systems recorded in the output file as a single tuple.

        @return: A 3-tuple of (C{UnitSystem}, C{FlowUnits}, list of
            C{ConcentrationUnits} — one per pollutant, or an empty list when
            no pollutants are present).
        @rtype: Tuple[UnitSystem, FlowUnits, Optional[List[ConcentrationUnits]]]
        """
        ...

    @property
    def flow_units(self) -> FlowUnits:
        """
        Flow unit system active throughout the simulation.

        @return: C{FlowUnits} enumeration member describing the flow units.
        @rtype: FlowUnits
        """
        ...

    @property
    def pollutant_units(self) -> List[ConcentrationUnits]:
        """
        Concentration unit for each pollutant modelled in the simulation.

        @return: List of C{ConcentrationUnits} members ordered by pollutant
            index.  Returns an empty list when no pollutants are present.
        @rtype: List[ConcentrationUnits]
        """
        ...

    @property
    def start_date(self) -> datetime:
        """
        Simulation start date and time decoded from the output file header.

        @return: Start date/time of the simulation as a C{datetime} object.
        @rtype: datetime
        """
        ...

    @property
    def times(self) -> List[datetime]:
        """
        Datetime object for every reporting period stored in the output file.

        The list begins at C{start_date + report_step} and contains exactly
        C{num_periods} entries, one per reporting interval.

        @return: Ordered list of reporting-period datetimes.
        @rtype: List[datetime]
        """
        ...

    # ====================================================================
    # Variable metadata
    # ====================================================================

    def get_num_variables(self, element_type: ElementType) -> int:
        """
        Return the number of result variables recorded for an element type.

        @param element_type: The SWMM element category to query.
        @type element_type: ElementType
        @return: Count of result variables stored per reporting period for
            C{element_type}.
        @rtype: int
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    def get_variable_code(self, element_type: ElementType, variable_index: int) -> int:
        """
        Return the integer code for a single result variable.

        @param element_type: The SWMM element category.
        @type element_type: ElementType
        @param variable_index: Zero-based index of the variable within the
            element type's variable list.
        @type variable_index: int
        @return: Integer variable code.
        @rtype: int
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    def get_variable_codes(self, element_type: ElementType) -> List[int]:
        """
        Return all result variable codes for an element type.

        @param element_type: The SWMM element category.
        @type element_type: ElementType
        @return: List of integer variable codes in variable-index order.
        @rtype: List[int]
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    def get_num_properties(self, element_type: ElementType) -> int:
        """
        Return the number of static properties recorded for an element type.

        @param element_type: The SWMM element category.
        @type element_type: ElementType
        @return: Count of static (time-invariant) properties for C{element_type}.
        @rtype: int
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    def get_property_code(self, element_type: ElementType, property_index: int) -> int:
        """
        Return the integer code for a single static property.

        @param element_type: The SWMM element category.
        @type element_type: ElementType
        @param property_index: Zero-based index of the property within the
            element type's property list.
        @type property_index: int
        @return: Integer property code.
        @rtype: int
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    def get_property_codes(self, element_type: ElementType) -> List[int]:
        """
        Return all static property codes for an element type.

        @param element_type: The SWMM element category.
        @type element_type: ElementType
        @return: List of integer property codes in property-index order.
        @rtype: List[int]
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    def get_property_value(self, element_type: ElementType, element_index: int, property_code: int) -> float:
        """
        Return a single static property value for a specific element.

        @param element_type: The SWMM element category.
        @type element_type: ElementType
        @param element_index: Zero-based element index or element name string.
        @type element_index: int
        @param property_code: Integer property code obtained from
            C{get_property_code}.
        @type property_code: int
        @return: Property value in the units recorded in the output file.
        @rtype: float
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    def get_property_values(self, element_type: ElementType, element_index: int) -> List[float]:
        """
        Return all static property values for a specific element.

        @param element_type: The SWMM element category.
        @type element_type: ElementType
        @param element_index: Zero-based element index or element name string.
        @type element_index: int
        @return: Ordered list of all property values for the element.
        @rtype: List[float]
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    # ====================================================================
    # Temporal attributes
    # ====================================================================

    def get_time_attribute(self, time_attribute: TimeAttribute) -> int:
        """
        Return a temporal meta-attribute from the output file header.

        @param time_attribute: The temporal attribute to retrieve
            (C{REPORT_STEP} returns step size in seconds;
            C{NUM_PERIODS} returns the total period count).
        @type time_attribute: TimeAttribute
        @return: Integer value of the requested temporal attribute.
        @rtype: int
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    # ====================================================================
    # Element names
    # ====================================================================

    def get_element_name(self, element_type: ElementType, element_index: int) -> str:
        """
        Return the name of a single SWMM element as recorded in the input file.

        @param element_type: The SWMM element category.
        @type element_type: ElementType
        @param element_index: Zero-based index of the element.
        @type element_index: int
        @return: Element name string.
        @rtype: str
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    def get_element_names(self, element_type: ElementType) -> List[str]:
        """
        Return the names of all elements of the given type.

        @param element_type: The SWMM element category.  May not be
            C{ElementType.SYSTEM}, which has no named instances.
        @type element_type: ElementType
        @return: Ordered list of element name strings (index matches element index).
        @rtype: List[str]
        @raise SWMMOutputException: If C{element_type} is C{SYSTEM} or the
            underlying C API call fails.
        """
        ...

    # ====================================================================
    # Per-element time series
    # ====================================================================

    def get_subcatchment_timeseries(self, element_index: Union[int, str], attribute: SubcatchAttribute, start_date_index: int = ..., end_date_index: int = ..., sub_index: int = ...) -> Dict[datetime, float]:
        """
        Return a time series for a subcatchment result attribute.

        @param element_index: Zero-based subcatchment index or subcatchment name string.
        @type element_index: Union[int, str]
        @param attribute: The subcatchment result attribute to extract.
        @type attribute: SubcatchAttribute
        @param start_date_index: Index into C{times} for the first period to
            retrieve (inclusive).  Defaults to C{0}.
        @type start_date_index: int
        @param end_date_index: Index into C{times} for the last period to
            retrieve (exclusive).  Use C{-1} to retrieve through the final period.
            Defaults to C{-1}.
        @type end_date_index: int
        @param sub_index: Offset added to C{attribute.value} to select a
            specific pollutant when C{attribute} is C{POLLUTANT_CONCENTRATION}.
            Defaults to C{0}.
        @type sub_index: int
        @return: Ordered mapping from reporting-period C{datetime} to attribute value.
        @rtype: Dict[datetime, float]
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    def get_node_timeseries(self, element_index: Union[int, str], attribute: NodeAttribute, start_date_index: int = ..., end_date_index: int = ..., sub_index: int = ...) -> Dict[datetime, float]:
        """
        Return a time series for a node result attribute.

        @param element_index: Zero-based node index or node name string.
        @type element_index: Union[int, str]
        @param attribute: The node result attribute to extract.
        @type attribute: NodeAttribute
        @param start_date_index: Index into C{times} for the first period to
            retrieve (inclusive).  Defaults to C{0}.
        @type start_date_index: int
        @param end_date_index: Index into C{times} for the last period to
            retrieve (exclusive).  Use C{-1} to retrieve through the final period.
            Defaults to C{-1}.
        @type end_date_index: int
        @param sub_index: Offset added to C{attribute.value} to select a
            specific pollutant when C{attribute} is C{POLLUTANT_CONCENTRATION}.
            Defaults to C{0}.
        @type sub_index: int
        @return: Ordered mapping from reporting-period C{datetime} to attribute value.
        @rtype: Dict[datetime, float]
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    def get_link_timeseries(self, element_index: Union[int, str], attribute: LinkAttribute, start_date_index: int = ..., end_date_index: int = ..., sub_index: int = ...) -> Dict[datetime, float]:
        """
        Return a time series for a link result attribute.

        @param element_index: Zero-based link index or link name string.
        @type element_index: Union[int, str]
        @param attribute: The link result attribute to extract.
        @type attribute: LinkAttribute
        @param start_date_index: Index into C{times} for the first period to
            retrieve (inclusive).  Defaults to C{0}.
        @type start_date_index: int
        @param end_date_index: Index into C{times} for the last period to
            retrieve (exclusive).  Use C{-1} to retrieve through the final period.
            Defaults to C{-1}.
        @type end_date_index: int
        @param sub_index: Offset added to C{attribute.value} to select a
            specific pollutant when C{attribute} is C{POLLUTANT_CONCENTRATION}.
            Defaults to C{0}.
        @type sub_index: int
        @return: Ordered mapping from reporting-period C{datetime} to attribute value.
        @rtype: Dict[datetime, float]
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    def get_system_timeseries(self, attribute: SystemAttribute, start_date_index: int = ..., end_date_index: int = ..., sub_index: int = ...) -> Dict[datetime, float]:
        """
        Return a time series for a system-level result attribute.

        @param attribute: The system result attribute to extract.
        @type attribute: SystemAttribute
        @param start_date_index: Index into C{times} for the first period to
            retrieve (inclusive).  Defaults to C{0}.
        @type start_date_index: int
        @param end_date_index: Index into C{times} for the last period to
            retrieve (exclusive).  Use C{-1} to retrieve through the final period.
            Defaults to C{-1}.
        @type end_date_index: int
        @param sub_index: Offset added to C{attribute.value} for extended
            attribute access.  Defaults to C{0}.
        @type sub_index: int
        @return: Ordered mapping from reporting-period C{datetime} to attribute value.
        @rtype: Dict[datetime, float]
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    # ====================================================================
    # Bulk reads — all elements at one time step
    # ====================================================================

    def get_subcatchment_values_by_time_and_attribute(self, time_index: int, attribute: SubcatchAttribute, sub_index: int = ...) -> Dict[str, float]:
        """
        Return a single result attribute for all subcatchments at one reporting step.

        @param time_index: Zero-based index into the reporting period list.
        @type time_index: int
        @param attribute: The subcatchment result attribute to extract.
        @type attribute: SubcatchAttribute
        @param sub_index: Offset added to C{attribute.value} to select a
            specific pollutant when C{attribute} is C{POLLUTANT_CONCENTRATION}.
            Defaults to C{0}.
        @type sub_index: int
        @return: Mapping from subcatchment name to attribute value for every
            subcatchment in the model.
        @rtype: Dict[str, float]
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    def get_node_values_by_time_and_attribute(self, time_index: int, attribute: NodeAttribute, sub_index: int = ...) -> Dict[str, float]:
        """
        Return a single result attribute for all nodes at one reporting step.

        @param time_index: Zero-based index into the reporting period list.
        @type time_index: int
        @param attribute: The node result attribute to extract.
        @type attribute: NodeAttribute
        @param sub_index: Offset added to C{attribute.value} to select a
            specific pollutant when C{attribute} is C{POLLUTANT_CONCENTRATION}.
            Defaults to C{0}.
        @type sub_index: int
        @return: Mapping from node name to attribute value for every node in
            the model.
        @rtype: Dict[str, float]
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    def get_link_values_by_time_and_attribute(self, time_index: int, attribute: LinkAttribute, sub_index: int = ...) -> Dict[str, float]:
        """
        Return a single result attribute for all links at one reporting step.

        @param time_index: Zero-based index into the reporting period list.
        @type time_index: int
        @param attribute: The link result attribute to extract.
        @type attribute: LinkAttribute
        @param sub_index: Offset added to C{attribute.value} to select a
            specific pollutant when C{attribute} is C{POLLUTANT_CONCENTRATION}.
            Defaults to C{0}.
        @type sub_index: int
        @return: Mapping from link name to attribute value for every link in
            the model.
        @rtype: Dict[str, float]
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    def get_system_values_by_time_and_attribute(self, time_index: int, attribute: SystemAttribute, sub_index: int = ...) -> Dict[str, float]:
        """
        Return a single system attribute value at one reporting step.

        @param time_index: Zero-based index into the reporting period list.
        @type time_index: int
        @param attribute: The system result attribute to extract.
        @type attribute: SystemAttribute
        @param sub_index: Offset added to C{attribute.value} for extended
            attribute access.  Defaults to C{0}.
        @type sub_index: int
        @return: Single-entry mapping from the C{SystemAttribute} name to its value.
        @rtype: Dict[str, float]
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    # ====================================================================
    # Convenience helpers — all attributes for one element at one time step
    # ====================================================================

    def get_subcatchment_values_by_time_and_element_index(self, time_index: int, element_index: Union[int, str]) -> Dict[str, float]:
        """
        Return all result attributes for a single subcatchment at one reporting step.

        Enumerated attributes are keyed by their C{SubcatchAttribute} name;
        pollutant entries are keyed by the pollutant element name.

        @param time_index: Zero-based index into the reporting period list.
        @type time_index: int
        @param element_index: Zero-based subcatchment index or subcatchment name string.
        @type element_index: Union[int, str]
        @return: Mapping from attribute/pollutant name to result value for all
            attributes of the specified subcatchment.
        @rtype: Dict[str, float]
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    def get_node_values_by_time_and_element_index(self, time_index: int, element_index: Union[int, str]) -> Dict[str, float]:
        """
        Return all result attributes for a single node at one reporting step.

        Enumerated attributes are keyed by their C{NodeAttribute} name;
        pollutant entries are keyed by the pollutant element name.

        @param time_index: Zero-based index into the reporting period list.
        @type time_index: int
        @param element_index: Zero-based node index or node name string.
        @type element_index: Union[int, str]
        @return: Mapping from attribute/pollutant name to result value for all
            attributes of the specified node.
        @rtype: Dict[str, float]
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    def get_link_values_by_time_and_element_index(self, time_index: int, element_index: Union[int, str]) -> Dict[str, float]:
        """
        Return all result attributes for a single link at one reporting step.

        Enumerated attributes are keyed by their C{LinkAttribute} name;
        pollutant entries are keyed by the pollutant element name.

        @param time_index: Zero-based index into the reporting period list.
        @type time_index: int
        @param element_index: Zero-based link index or link name string.
        @type element_index: Union[int, str]
        @return: Mapping from attribute/pollutant name to result value for all
            attributes of the specified link.
        @rtype: Dict[str, float]
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...

    def get_system_values_by_time(self, time_index: int) -> Dict[str, float]:
        """
        Return all system-level result attributes at one reporting step.

        Each key is the C{SystemAttribute} member name for the corresponding variable.

        @param time_index: Zero-based index into the reporting period list.
        @type time_index: int
        @return: Mapping from system attribute name to result value, covering
            all C{SystemAttribute} members.
        @rtype: Dict[str, float]
        @raise SWMMOutputException: If the underlying C API call fails.
        """
        ...
